package org.prcode.business.basedomain.loginNo.domain;

import java.util.Date;
import org.prcode.basedomain.base.BaseDomain;

public class LoginNo extends BaseDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_no.f_id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_no.f_no
     *
     * @mbg.generated
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_no.f_password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_no.f_type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_no.f_val_level
     *
     * @mbg.generated
     */
    private Integer valLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_no.f_status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_no.t_user_f_id
     *
     * @mbg.generated
     */
    private Long userFId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_no.f_sys0_del_time
     *
     * @mbg.generated
     */
    private Date sys0DelTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_no.f_sys0_del_state
     *
     * @mbg.generated
     */
    private Byte sys0DelState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_no.f_old_pwd
     *
     * @mbg.generated
     */
    private String oldPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_no.f_union_id
     *
     * @mbg.generated
     */
    private String unionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_no.f_create_type
     *
     * @mbg.generated
     */
    private Byte createType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_no.f_id
     *
     * @return the value of t_login_no.f_id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_no.f_id
     *
     * @param id the value for t_login_no.f_id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_no.f_no
     *
     * @return the value of t_login_no.f_no
     *
     * @mbg.generated
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_no.f_no
     *
     * @param no the value for t_login_no.f_no
     *
     * @mbg.generated
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_no.f_password
     *
     * @return the value of t_login_no.f_password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_no.f_password
     *
     * @param password the value for t_login_no.f_password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_no.f_type
     *
     * @return the value of t_login_no.f_type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_no.f_type
     *
     * @param type the value for t_login_no.f_type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_no.f_val_level
     *
     * @return the value of t_login_no.f_val_level
     *
     * @mbg.generated
     */
    public Integer getValLevel() {
        return valLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_no.f_val_level
     *
     * @param valLevel the value for t_login_no.f_val_level
     *
     * @mbg.generated
     */
    public void setValLevel(Integer valLevel) {
        this.valLevel = valLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_no.f_status
     *
     * @return the value of t_login_no.f_status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_no.f_status
     *
     * @param status the value for t_login_no.f_status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_no.t_user_f_id
     *
     * @return the value of t_login_no.t_user_f_id
     *
     * @mbg.generated
     */
    public Long getUserFId() {
        return userFId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_no.t_user_f_id
     *
     * @param userFId the value for t_login_no.t_user_f_id
     *
     * @mbg.generated
     */
    public void setUserFId(Long userFId) {
        this.userFId = userFId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_no.f_sys0_del_time
     *
     * @return the value of t_login_no.f_sys0_del_time
     *
     * @mbg.generated
     */
    public Date getSys0DelTime() {
        return sys0DelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_no.f_sys0_del_time
     *
     * @param sys0DelTime the value for t_login_no.f_sys0_del_time
     *
     * @mbg.generated
     */
    public void setSys0DelTime(Date sys0DelTime) {
        this.sys0DelTime = sys0DelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_no.f_sys0_del_state
     *
     * @return the value of t_login_no.f_sys0_del_state
     *
     * @mbg.generated
     */
    public Byte getSys0DelState() {
        return sys0DelState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_no.f_sys0_del_state
     *
     * @param sys0DelState the value for t_login_no.f_sys0_del_state
     *
     * @mbg.generated
     */
    public void setSys0DelState(Byte sys0DelState) {
        this.sys0DelState = sys0DelState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_no.f_old_pwd
     *
     * @return the value of t_login_no.f_old_pwd
     *
     * @mbg.generated
     */
    public String getOldPwd() {
        return oldPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_no.f_old_pwd
     *
     * @param oldPwd the value for t_login_no.f_old_pwd
     *
     * @mbg.generated
     */
    public void setOldPwd(String oldPwd) {
        this.oldPwd = oldPwd == null ? null : oldPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_no.f_union_id
     *
     * @return the value of t_login_no.f_union_id
     *
     * @mbg.generated
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_no.f_union_id
     *
     * @param unionId the value for t_login_no.f_union_id
     *
     * @mbg.generated
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId == null ? null : unionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_no.f_create_type
     *
     * @return the value of t_login_no.f_create_type
     *
     * @mbg.generated
     */
    public Byte getCreateType() {
        return createType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_no.f_create_type
     *
     * @param createType the value for t_login_no.f_create_type
     *
     * @mbg.generated
     */
    public void setCreateType(Byte createType) {
        this.createType = createType;
    }
}