package org.prcode.business.basedomain.loginNo.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LoginNoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    public LoginNoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("loginNo.f_id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("loginNo.f_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("loginNo.f_id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("loginNo.f_id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("loginNo.f_id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("loginNo.f_id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("loginNo.f_id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("loginNo.f_id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("loginNo.f_id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("loginNo.f_id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("loginNo.f_id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("loginNo.f_id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNoIsNull() {
            addCriterion("loginNo.f_no is null");
            return (Criteria) this;
        }

        public Criteria andNoIsNotNull() {
            addCriterion("loginNo.f_no is not null");
            return (Criteria) this;
        }

        public Criteria andNoEqualTo(String value) {
            addCriterion("loginNo.f_no =", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotEqualTo(String value) {
            addCriterion("loginNo.f_no <>", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoGreaterThan(String value) {
            addCriterion("loginNo.f_no >", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoGreaterThanOrEqualTo(String value) {
            addCriterion("loginNo.f_no >=", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoLessThan(String value) {
            addCriterion("loginNo.f_no <", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoLessThanOrEqualTo(String value) {
            addCriterion("loginNo.f_no <=", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoLike(String value) {
            addCriterion("loginNo.f_no like", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotLike(String value) {
            addCriterion("loginNo.f_no not like", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoIn(List<String> values) {
            addCriterion("loginNo.f_no in", values, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotIn(List<String> values) {
            addCriterion("loginNo.f_no not in", values, "no");
            return (Criteria) this;
        }

        public Criteria andNoBetween(String value1, String value2) {
            addCriterion("loginNo.f_no between", value1, value2, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotBetween(String value1, String value2) {
            addCriterion("loginNo.f_no not between", value1, value2, "no");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("loginNo.f_password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("loginNo.f_password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("loginNo.f_password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("loginNo.f_password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("loginNo.f_password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("loginNo.f_password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("loginNo.f_password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("loginNo.f_password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("loginNo.f_password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("loginNo.f_password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("loginNo.f_password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("loginNo.f_password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("loginNo.f_password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("loginNo.f_password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("loginNo.f_type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("loginNo.f_type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("loginNo.f_type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("loginNo.f_type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("loginNo.f_type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("loginNo.f_type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("loginNo.f_type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("loginNo.f_type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("loginNo.f_type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("loginNo.f_type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("loginNo.f_type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("loginNo.f_type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andValLevelIsNull() {
            addCriterion("loginNo.f_val_level is null");
            return (Criteria) this;
        }

        public Criteria andValLevelIsNotNull() {
            addCriterion("loginNo.f_val_level is not null");
            return (Criteria) this;
        }

        public Criteria andValLevelEqualTo(Integer value) {
            addCriterion("loginNo.f_val_level =", value, "valLevel");
            return (Criteria) this;
        }

        public Criteria andValLevelNotEqualTo(Integer value) {
            addCriterion("loginNo.f_val_level <>", value, "valLevel");
            return (Criteria) this;
        }

        public Criteria andValLevelGreaterThan(Integer value) {
            addCriterion("loginNo.f_val_level >", value, "valLevel");
            return (Criteria) this;
        }

        public Criteria andValLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("loginNo.f_val_level >=", value, "valLevel");
            return (Criteria) this;
        }

        public Criteria andValLevelLessThan(Integer value) {
            addCriterion("loginNo.f_val_level <", value, "valLevel");
            return (Criteria) this;
        }

        public Criteria andValLevelLessThanOrEqualTo(Integer value) {
            addCriterion("loginNo.f_val_level <=", value, "valLevel");
            return (Criteria) this;
        }

        public Criteria andValLevelIn(List<Integer> values) {
            addCriterion("loginNo.f_val_level in", values, "valLevel");
            return (Criteria) this;
        }

        public Criteria andValLevelNotIn(List<Integer> values) {
            addCriterion("loginNo.f_val_level not in", values, "valLevel");
            return (Criteria) this;
        }

        public Criteria andValLevelBetween(Integer value1, Integer value2) {
            addCriterion("loginNo.f_val_level between", value1, value2, "valLevel");
            return (Criteria) this;
        }

        public Criteria andValLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("loginNo.f_val_level not between", value1, value2, "valLevel");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("loginNo.f_status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("loginNo.f_status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("loginNo.f_status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("loginNo.f_status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("loginNo.f_status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("loginNo.f_status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("loginNo.f_status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("loginNo.f_status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("loginNo.f_status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("loginNo.f_status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("loginNo.f_status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("loginNo.f_status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andUserFIdIsNull() {
            addCriterion("loginNo.t_user_f_id is null");
            return (Criteria) this;
        }

        public Criteria andUserFIdIsNotNull() {
            addCriterion("loginNo.t_user_f_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserFIdEqualTo(Long value) {
            addCriterion("loginNo.t_user_f_id =", value, "userFId");
            return (Criteria) this;
        }

        public Criteria andUserFIdNotEqualTo(Long value) {
            addCriterion("loginNo.t_user_f_id <>", value, "userFId");
            return (Criteria) this;
        }

        public Criteria andUserFIdGreaterThan(Long value) {
            addCriterion("loginNo.t_user_f_id >", value, "userFId");
            return (Criteria) this;
        }

        public Criteria andUserFIdGreaterThanOrEqualTo(Long value) {
            addCriterion("loginNo.t_user_f_id >=", value, "userFId");
            return (Criteria) this;
        }

        public Criteria andUserFIdLessThan(Long value) {
            addCriterion("loginNo.t_user_f_id <", value, "userFId");
            return (Criteria) this;
        }

        public Criteria andUserFIdLessThanOrEqualTo(Long value) {
            addCriterion("loginNo.t_user_f_id <=", value, "userFId");
            return (Criteria) this;
        }

        public Criteria andUserFIdIn(List<Long> values) {
            addCriterion("loginNo.t_user_f_id in", values, "userFId");
            return (Criteria) this;
        }

        public Criteria andUserFIdNotIn(List<Long> values) {
            addCriterion("loginNo.t_user_f_id not in", values, "userFId");
            return (Criteria) this;
        }

        public Criteria andUserFIdBetween(Long value1, Long value2) {
            addCriterion("loginNo.t_user_f_id between", value1, value2, "userFId");
            return (Criteria) this;
        }

        public Criteria andUserFIdNotBetween(Long value1, Long value2) {
            addCriterion("loginNo.t_user_f_id not between", value1, value2, "userFId");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeIsNull() {
            addCriterion("loginNo.f_sys0_add_time is null");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeIsNotNull() {
            addCriterion("loginNo.f_sys0_add_time is not null");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeEqualTo(Date value) {
            addCriterion("loginNo.f_sys0_add_time =", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeNotEqualTo(Date value) {
            addCriterion("loginNo.f_sys0_add_time <>", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeGreaterThan(Date value) {
            addCriterion("loginNo.f_sys0_add_time >", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("loginNo.f_sys0_add_time >=", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeLessThan(Date value) {
            addCriterion("loginNo.f_sys0_add_time <", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeLessThanOrEqualTo(Date value) {
            addCriterion("loginNo.f_sys0_add_time <=", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeIn(List<Date> values) {
            addCriterion("loginNo.f_sys0_add_time in", values, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeNotIn(List<Date> values) {
            addCriterion("loginNo.f_sys0_add_time not in", values, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeBetween(Date value1, Date value2) {
            addCriterion("loginNo.f_sys0_add_time between", value1, value2, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeNotBetween(Date value1, Date value2) {
            addCriterion("loginNo.f_sys0_add_time not between", value1, value2, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeIsNull() {
            addCriterion("loginNo.f_sys0_upd_time is null");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeIsNotNull() {
            addCriterion("loginNo.f_sys0_upd_time is not null");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeEqualTo(Date value) {
            addCriterion("loginNo.f_sys0_upd_time =", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeNotEqualTo(Date value) {
            addCriterion("loginNo.f_sys0_upd_time <>", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeGreaterThan(Date value) {
            addCriterion("loginNo.f_sys0_upd_time >", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("loginNo.f_sys0_upd_time >=", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeLessThan(Date value) {
            addCriterion("loginNo.f_sys0_upd_time <", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeLessThanOrEqualTo(Date value) {
            addCriterion("loginNo.f_sys0_upd_time <=", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeIn(List<Date> values) {
            addCriterion("loginNo.f_sys0_upd_time in", values, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeNotIn(List<Date> values) {
            addCriterion("loginNo.f_sys0_upd_time not in", values, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeBetween(Date value1, Date value2) {
            addCriterion("loginNo.f_sys0_upd_time between", value1, value2, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeNotBetween(Date value1, Date value2) {
            addCriterion("loginNo.f_sys0_upd_time not between", value1, value2, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeIsNull() {
            addCriterion("loginNo.f_sys0_del_time is null");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeIsNotNull() {
            addCriterion("loginNo.f_sys0_del_time is not null");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeEqualTo(Date value) {
            addCriterion("loginNo.f_sys0_del_time =", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeNotEqualTo(Date value) {
            addCriterion("loginNo.f_sys0_del_time <>", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeGreaterThan(Date value) {
            addCriterion("loginNo.f_sys0_del_time >", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("loginNo.f_sys0_del_time >=", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeLessThan(Date value) {
            addCriterion("loginNo.f_sys0_del_time <", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeLessThanOrEqualTo(Date value) {
            addCriterion("loginNo.f_sys0_del_time <=", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeIn(List<Date> values) {
            addCriterion("loginNo.f_sys0_del_time in", values, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeNotIn(List<Date> values) {
            addCriterion("loginNo.f_sys0_del_time not in", values, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeBetween(Date value1, Date value2) {
            addCriterion("loginNo.f_sys0_del_time between", value1, value2, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeNotBetween(Date value1, Date value2) {
            addCriterion("loginNo.f_sys0_del_time not between", value1, value2, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserIsNull() {
            addCriterion("loginNo.f_sys0_add_user is null");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserIsNotNull() {
            addCriterion("loginNo.f_sys0_add_user is not null");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserEqualTo(Long value) {
            addCriterion("loginNo.f_sys0_add_user =", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserNotEqualTo(Long value) {
            addCriterion("loginNo.f_sys0_add_user <>", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserGreaterThan(Long value) {
            addCriterion("loginNo.f_sys0_add_user >", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserGreaterThanOrEqualTo(Long value) {
            addCriterion("loginNo.f_sys0_add_user >=", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserLessThan(Long value) {
            addCriterion("loginNo.f_sys0_add_user <", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserLessThanOrEqualTo(Long value) {
            addCriterion("loginNo.f_sys0_add_user <=", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserIn(List<Long> values) {
            addCriterion("loginNo.f_sys0_add_user in", values, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserNotIn(List<Long> values) {
            addCriterion("loginNo.f_sys0_add_user not in", values, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserBetween(Long value1, Long value2) {
            addCriterion("loginNo.f_sys0_add_user between", value1, value2, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserNotBetween(Long value1, Long value2) {
            addCriterion("loginNo.f_sys0_add_user not between", value1, value2, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserIsNull() {
            addCriterion("loginNo.f_sys0_upd_user is null");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserIsNotNull() {
            addCriterion("loginNo.f_sys0_upd_user is not null");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserEqualTo(Long value) {
            addCriterion("loginNo.f_sys0_upd_user =", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserNotEqualTo(Long value) {
            addCriterion("loginNo.f_sys0_upd_user <>", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserGreaterThan(Long value) {
            addCriterion("loginNo.f_sys0_upd_user >", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserGreaterThanOrEqualTo(Long value) {
            addCriterion("loginNo.f_sys0_upd_user >=", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserLessThan(Long value) {
            addCriterion("loginNo.f_sys0_upd_user <", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserLessThanOrEqualTo(Long value) {
            addCriterion("loginNo.f_sys0_upd_user <=", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserIn(List<Long> values) {
            addCriterion("loginNo.f_sys0_upd_user in", values, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserNotIn(List<Long> values) {
            addCriterion("loginNo.f_sys0_upd_user not in", values, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserBetween(Long value1, Long value2) {
            addCriterion("loginNo.f_sys0_upd_user between", value1, value2, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserNotBetween(Long value1, Long value2) {
            addCriterion("loginNo.f_sys0_upd_user not between", value1, value2, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserIsNull() {
            addCriterion("loginNo.f_sys0_del_user is null");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserIsNotNull() {
            addCriterion("loginNo.f_sys0_del_user is not null");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserEqualTo(Long value) {
            addCriterion("loginNo.f_sys0_del_user =", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserNotEqualTo(Long value) {
            addCriterion("loginNo.f_sys0_del_user <>", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserGreaterThan(Long value) {
            addCriterion("loginNo.f_sys0_del_user >", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserGreaterThanOrEqualTo(Long value) {
            addCriterion("loginNo.f_sys0_del_user >=", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserLessThan(Long value) {
            addCriterion("loginNo.f_sys0_del_user <", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserLessThanOrEqualTo(Long value) {
            addCriterion("loginNo.f_sys0_del_user <=", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserIn(List<Long> values) {
            addCriterion("loginNo.f_sys0_del_user in", values, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserNotIn(List<Long> values) {
            addCriterion("loginNo.f_sys0_del_user not in", values, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserBetween(Long value1, Long value2) {
            addCriterion("loginNo.f_sys0_del_user between", value1, value2, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserNotBetween(Long value1, Long value2) {
            addCriterion("loginNo.f_sys0_del_user not between", value1, value2, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateIsNull() {
            addCriterion("loginNo.f_sys0_del_state is null");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateIsNotNull() {
            addCriterion("loginNo.f_sys0_del_state is not null");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateEqualTo(Byte value) {
            addCriterion("loginNo.f_sys0_del_state =", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateNotEqualTo(Byte value) {
            addCriterion("loginNo.f_sys0_del_state <>", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateGreaterThan(Byte value) {
            addCriterion("loginNo.f_sys0_del_state >", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("loginNo.f_sys0_del_state >=", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateLessThan(Byte value) {
            addCriterion("loginNo.f_sys0_del_state <", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateLessThanOrEqualTo(Byte value) {
            addCriterion("loginNo.f_sys0_del_state <=", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateIn(List<Byte> values) {
            addCriterion("loginNo.f_sys0_del_state in", values, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateNotIn(List<Byte> values) {
            addCriterion("loginNo.f_sys0_del_state not in", values, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateBetween(Byte value1, Byte value2) {
            addCriterion("loginNo.f_sys0_del_state between", value1, value2, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateNotBetween(Byte value1, Byte value2) {
            addCriterion("loginNo.f_sys0_del_state not between", value1, value2, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andOldPwdIsNull() {
            addCriterion("loginNo.f_old_pwd is null");
            return (Criteria) this;
        }

        public Criteria andOldPwdIsNotNull() {
            addCriterion("loginNo.f_old_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andOldPwdEqualTo(String value) {
            addCriterion("loginNo.f_old_pwd =", value, "oldPwd");
            return (Criteria) this;
        }

        public Criteria andOldPwdNotEqualTo(String value) {
            addCriterion("loginNo.f_old_pwd <>", value, "oldPwd");
            return (Criteria) this;
        }

        public Criteria andOldPwdGreaterThan(String value) {
            addCriterion("loginNo.f_old_pwd >", value, "oldPwd");
            return (Criteria) this;
        }

        public Criteria andOldPwdGreaterThanOrEqualTo(String value) {
            addCriterion("loginNo.f_old_pwd >=", value, "oldPwd");
            return (Criteria) this;
        }

        public Criteria andOldPwdLessThan(String value) {
            addCriterion("loginNo.f_old_pwd <", value, "oldPwd");
            return (Criteria) this;
        }

        public Criteria andOldPwdLessThanOrEqualTo(String value) {
            addCriterion("loginNo.f_old_pwd <=", value, "oldPwd");
            return (Criteria) this;
        }

        public Criteria andOldPwdLike(String value) {
            addCriterion("loginNo.f_old_pwd like", value, "oldPwd");
            return (Criteria) this;
        }

        public Criteria andOldPwdNotLike(String value) {
            addCriterion("loginNo.f_old_pwd not like", value, "oldPwd");
            return (Criteria) this;
        }

        public Criteria andOldPwdIn(List<String> values) {
            addCriterion("loginNo.f_old_pwd in", values, "oldPwd");
            return (Criteria) this;
        }

        public Criteria andOldPwdNotIn(List<String> values) {
            addCriterion("loginNo.f_old_pwd not in", values, "oldPwd");
            return (Criteria) this;
        }

        public Criteria andOldPwdBetween(String value1, String value2) {
            addCriterion("loginNo.f_old_pwd between", value1, value2, "oldPwd");
            return (Criteria) this;
        }

        public Criteria andOldPwdNotBetween(String value1, String value2) {
            addCriterion("loginNo.f_old_pwd not between", value1, value2, "oldPwd");
            return (Criteria) this;
        }

        public Criteria andUnionIdIsNull() {
            addCriterion("loginNo.f_union_id is null");
            return (Criteria) this;
        }

        public Criteria andUnionIdIsNotNull() {
            addCriterion("loginNo.f_union_id is not null");
            return (Criteria) this;
        }

        public Criteria andUnionIdEqualTo(String value) {
            addCriterion("loginNo.f_union_id =", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdNotEqualTo(String value) {
            addCriterion("loginNo.f_union_id <>", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdGreaterThan(String value) {
            addCriterion("loginNo.f_union_id >", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdGreaterThanOrEqualTo(String value) {
            addCriterion("loginNo.f_union_id >=", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdLessThan(String value) {
            addCriterion("loginNo.f_union_id <", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdLessThanOrEqualTo(String value) {
            addCriterion("loginNo.f_union_id <=", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdLike(String value) {
            addCriterion("loginNo.f_union_id like", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdNotLike(String value) {
            addCriterion("loginNo.f_union_id not like", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdIn(List<String> values) {
            addCriterion("loginNo.f_union_id in", values, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdNotIn(List<String> values) {
            addCriterion("loginNo.f_union_id not in", values, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdBetween(String value1, String value2) {
            addCriterion("loginNo.f_union_id between", value1, value2, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdNotBetween(String value1, String value2) {
            addCriterion("loginNo.f_union_id not between", value1, value2, "unionId");
            return (Criteria) this;
        }

        public Criteria andCreateTypeIsNull() {
            addCriterion("loginNo.f_create_type is null");
            return (Criteria) this;
        }

        public Criteria andCreateTypeIsNotNull() {
            addCriterion("loginNo.f_create_type is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTypeEqualTo(Byte value) {
            addCriterion("loginNo.f_create_type =", value, "createType");
            return (Criteria) this;
        }

        public Criteria andCreateTypeNotEqualTo(Byte value) {
            addCriterion("loginNo.f_create_type <>", value, "createType");
            return (Criteria) this;
        }

        public Criteria andCreateTypeGreaterThan(Byte value) {
            addCriterion("loginNo.f_create_type >", value, "createType");
            return (Criteria) this;
        }

        public Criteria andCreateTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("loginNo.f_create_type >=", value, "createType");
            return (Criteria) this;
        }

        public Criteria andCreateTypeLessThan(Byte value) {
            addCriterion("loginNo.f_create_type <", value, "createType");
            return (Criteria) this;
        }

        public Criteria andCreateTypeLessThanOrEqualTo(Byte value) {
            addCriterion("loginNo.f_create_type <=", value, "createType");
            return (Criteria) this;
        }

        public Criteria andCreateTypeIn(List<Byte> values) {
            addCriterion("loginNo.f_create_type in", values, "createType");
            return (Criteria) this;
        }

        public Criteria andCreateTypeNotIn(List<Byte> values) {
            addCriterion("loginNo.f_create_type not in", values, "createType");
            return (Criteria) this;
        }

        public Criteria andCreateTypeBetween(Byte value1, Byte value2) {
            addCriterion("loginNo.f_create_type between", value1, value2, "createType");
            return (Criteria) this;
        }

        public Criteria andCreateTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("loginNo.f_create_type not between", value1, value2, "createType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_login_no
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_login_no
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}