package org.prcode.log.basedomain.managerLogger.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.prcode.log.basedomain.managerLogger.domain.ManagerLogger;
import org.prcode.log.basedomain.managerLogger.domain.ManagerLoggerExample;
import org.springframework.stereotype.Repository;

@Repository
public interface ManagerLoggerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    long countByExample(ManagerLoggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    int insert(ManagerLogger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    int insertSelective(ManagerLogger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    List<ManagerLogger> selectByExampleWithBLOBs(ManagerLoggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    List<ManagerLogger> selectByExample(ManagerLoggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    ManagerLogger selectByPrimaryKey(@Param("id") Long id, @Param("reqStartTime") Date reqStartTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManagerLogger record, @Param("example") ManagerLoggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ManagerLogger record, @Param("example") ManagerLoggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManagerLogger record, @Param("example") ManagerLoggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManagerLogger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ManagerLogger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManagerLogger record);
}