package org.prcode.basedomain.log.managerLogger.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ManagerLoggerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    public ManagerLoggerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("managerLogger.f_id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("managerLogger.f_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("managerLogger.f_id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("managerLogger.f_id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("managerLogger.f_id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("managerLogger.f_id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("managerLogger.f_id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("managerLogger.f_id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("managerLogger.f_id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("managerLogger.f_id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("managerLogger.f_id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("managerLogger.f_id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeIsNull() {
            addCriterion("managerLogger.f_req_start_time is null");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeIsNotNull() {
            addCriterion("managerLogger.f_req_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeEqualTo(Date value) {
            addCriterion("managerLogger.f_req_start_time =", value, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeNotEqualTo(Date value) {
            addCriterion("managerLogger.f_req_start_time <>", value, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeGreaterThan(Date value) {
            addCriterion("managerLogger.f_req_start_time >", value, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("managerLogger.f_req_start_time >=", value, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeLessThan(Date value) {
            addCriterion("managerLogger.f_req_start_time <", value, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("managerLogger.f_req_start_time <=", value, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeIn(List<Date> values) {
            addCriterion("managerLogger.f_req_start_time in", values, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeNotIn(List<Date> values) {
            addCriterion("managerLogger.f_req_start_time not in", values, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeBetween(Date value1, Date value2) {
            addCriterion("managerLogger.f_req_start_time between", value1, value2, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andReqStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("managerLogger.f_req_start_time not between", value1, value2, "reqStartTime");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("managerLogger.f_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("managerLogger.f_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("managerLogger.f_user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("managerLogger.f_user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("managerLogger.f_user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("managerLogger.f_user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("managerLogger.f_user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("managerLogger.f_user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("managerLogger.f_user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("managerLogger.f_user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("managerLogger.f_user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("managerLogger.f_user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserAccNoIsNull() {
            addCriterion("managerLogger.f_user_acc_no is null");
            return (Criteria) this;
        }

        public Criteria andUserAccNoIsNotNull() {
            addCriterion("managerLogger.f_user_acc_no is not null");
            return (Criteria) this;
        }

        public Criteria andUserAccNoEqualTo(String value) {
            addCriterion("managerLogger.f_user_acc_no =", value, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccNoNotEqualTo(String value) {
            addCriterion("managerLogger.f_user_acc_no <>", value, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccNoGreaterThan(String value) {
            addCriterion("managerLogger.f_user_acc_no >", value, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccNoGreaterThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_user_acc_no >=", value, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccNoLessThan(String value) {
            addCriterion("managerLogger.f_user_acc_no <", value, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccNoLessThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_user_acc_no <=", value, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccNoLike(String value) {
            addCriterion("managerLogger.f_user_acc_no like", value, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccNoNotLike(String value) {
            addCriterion("managerLogger.f_user_acc_no not like", value, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccNoIn(List<String> values) {
            addCriterion("managerLogger.f_user_acc_no in", values, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccNoNotIn(List<String> values) {
            addCriterion("managerLogger.f_user_acc_no not in", values, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccNoBetween(String value1, String value2) {
            addCriterion("managerLogger.f_user_acc_no between", value1, value2, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccNoNotBetween(String value1, String value2) {
            addCriterion("managerLogger.f_user_acc_no not between", value1, value2, "userAccNo");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeIsNull() {
            addCriterion("managerLogger.f_user_acc_type is null");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeIsNotNull() {
            addCriterion("managerLogger.f_user_acc_type is not null");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeEqualTo(Integer value) {
            addCriterion("managerLogger.f_user_acc_type =", value, "userAccType");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeNotEqualTo(Integer value) {
            addCriterion("managerLogger.f_user_acc_type <>", value, "userAccType");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeGreaterThan(Integer value) {
            addCriterion("managerLogger.f_user_acc_type >", value, "userAccType");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("managerLogger.f_user_acc_type >=", value, "userAccType");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeLessThan(Integer value) {
            addCriterion("managerLogger.f_user_acc_type <", value, "userAccType");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeLessThanOrEqualTo(Integer value) {
            addCriterion("managerLogger.f_user_acc_type <=", value, "userAccType");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeIn(List<Integer> values) {
            addCriterion("managerLogger.f_user_acc_type in", values, "userAccType");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeNotIn(List<Integer> values) {
            addCriterion("managerLogger.f_user_acc_type not in", values, "userAccType");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeBetween(Integer value1, Integer value2) {
            addCriterion("managerLogger.f_user_acc_type between", value1, value2, "userAccType");
            return (Criteria) this;
        }

        public Criteria andUserAccTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("managerLogger.f_user_acc_type not between", value1, value2, "userAccType");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailIsNull() {
            addCriterion("managerLogger.f_action_url_tail is null");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailIsNotNull() {
            addCriterion("managerLogger.f_action_url_tail is not null");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailEqualTo(String value) {
            addCriterion("managerLogger.f_action_url_tail =", value, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailNotEqualTo(String value) {
            addCriterion("managerLogger.f_action_url_tail <>", value, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailGreaterThan(String value) {
            addCriterion("managerLogger.f_action_url_tail >", value, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailGreaterThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_action_url_tail >=", value, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailLessThan(String value) {
            addCriterion("managerLogger.f_action_url_tail <", value, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailLessThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_action_url_tail <=", value, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailLike(String value) {
            addCriterion("managerLogger.f_action_url_tail like", value, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailNotLike(String value) {
            addCriterion("managerLogger.f_action_url_tail not like", value, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailIn(List<String> values) {
            addCriterion("managerLogger.f_action_url_tail in", values, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailNotIn(List<String> values) {
            addCriterion("managerLogger.f_action_url_tail not in", values, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailBetween(String value1, String value2) {
            addCriterion("managerLogger.f_action_url_tail between", value1, value2, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionUrlTailNotBetween(String value1, String value2) {
            addCriterion("managerLogger.f_action_url_tail not between", value1, value2, "actionUrlTail");
            return (Criteria) this;
        }

        public Criteria andActionDescIsNull() {
            addCriterion("managerLogger.f_action_desc is null");
            return (Criteria) this;
        }

        public Criteria andActionDescIsNotNull() {
            addCriterion("managerLogger.f_action_desc is not null");
            return (Criteria) this;
        }

        public Criteria andActionDescEqualTo(String value) {
            addCriterion("managerLogger.f_action_desc =", value, "actionDesc");
            return (Criteria) this;
        }

        public Criteria andActionDescNotEqualTo(String value) {
            addCriterion("managerLogger.f_action_desc <>", value, "actionDesc");
            return (Criteria) this;
        }

        public Criteria andActionDescGreaterThan(String value) {
            addCriterion("managerLogger.f_action_desc >", value, "actionDesc");
            return (Criteria) this;
        }

        public Criteria andActionDescGreaterThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_action_desc >=", value, "actionDesc");
            return (Criteria) this;
        }

        public Criteria andActionDescLessThan(String value) {
            addCriterion("managerLogger.f_action_desc <", value, "actionDesc");
            return (Criteria) this;
        }

        public Criteria andActionDescLessThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_action_desc <=", value, "actionDesc");
            return (Criteria) this;
        }

        public Criteria andActionDescLike(String value) {
            addCriterion("managerLogger.f_action_desc like", value, "actionDesc");
            return (Criteria) this;
        }

        public Criteria andActionDescNotLike(String value) {
            addCriterion("managerLogger.f_action_desc not like", value, "actionDesc");
            return (Criteria) this;
        }

        public Criteria andActionDescIn(List<String> values) {
            addCriterion("managerLogger.f_action_desc in", values, "actionDesc");
            return (Criteria) this;
        }

        public Criteria andActionDescNotIn(List<String> values) {
            addCriterion("managerLogger.f_action_desc not in", values, "actionDesc");
            return (Criteria) this;
        }

        public Criteria andActionDescBetween(String value1, String value2) {
            addCriterion("managerLogger.f_action_desc between", value1, value2, "actionDesc");
            return (Criteria) this;
        }

        public Criteria andActionDescNotBetween(String value1, String value2) {
            addCriterion("managerLogger.f_action_desc not between", value1, value2, "actionDesc");
            return (Criteria) this;
        }

        public Criteria andActionResStatusIsNull() {
            addCriterion("managerLogger.f_action_res_status is null");
            return (Criteria) this;
        }

        public Criteria andActionResStatusIsNotNull() {
            addCriterion("managerLogger.f_action_res_status is not null");
            return (Criteria) this;
        }

        public Criteria andActionResStatusEqualTo(String value) {
            addCriterion("managerLogger.f_action_res_status =", value, "actionResStatus");
            return (Criteria) this;
        }

        public Criteria andActionResStatusNotEqualTo(String value) {
            addCriterion("managerLogger.f_action_res_status <>", value, "actionResStatus");
            return (Criteria) this;
        }

        public Criteria andActionResStatusGreaterThan(String value) {
            addCriterion("managerLogger.f_action_res_status >", value, "actionResStatus");
            return (Criteria) this;
        }

        public Criteria andActionResStatusGreaterThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_action_res_status >=", value, "actionResStatus");
            return (Criteria) this;
        }

        public Criteria andActionResStatusLessThan(String value) {
            addCriterion("managerLogger.f_action_res_status <", value, "actionResStatus");
            return (Criteria) this;
        }

        public Criteria andActionResStatusLessThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_action_res_status <=", value, "actionResStatus");
            return (Criteria) this;
        }

        public Criteria andActionResStatusLike(String value) {
            addCriterion("managerLogger.f_action_res_status like", value, "actionResStatus");
            return (Criteria) this;
        }

        public Criteria andActionResStatusNotLike(String value) {
            addCriterion("managerLogger.f_action_res_status not like", value, "actionResStatus");
            return (Criteria) this;
        }

        public Criteria andActionResStatusIn(List<String> values) {
            addCriterion("managerLogger.f_action_res_status in", values, "actionResStatus");
            return (Criteria) this;
        }

        public Criteria andActionResStatusNotIn(List<String> values) {
            addCriterion("managerLogger.f_action_res_status not in", values, "actionResStatus");
            return (Criteria) this;
        }

        public Criteria andActionResStatusBetween(String value1, String value2) {
            addCriterion("managerLogger.f_action_res_status between", value1, value2, "actionResStatus");
            return (Criteria) this;
        }

        public Criteria andActionResStatusNotBetween(String value1, String value2) {
            addCriterion("managerLogger.f_action_res_status not between", value1, value2, "actionResStatus");
            return (Criteria) this;
        }

        public Criteria andActionResCodeIsNull() {
            addCriterion("managerLogger.f_action_res_code is null");
            return (Criteria) this;
        }

        public Criteria andActionResCodeIsNotNull() {
            addCriterion("managerLogger.f_action_res_code is not null");
            return (Criteria) this;
        }

        public Criteria andActionResCodeEqualTo(String value) {
            addCriterion("managerLogger.f_action_res_code =", value, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andActionResCodeNotEqualTo(String value) {
            addCriterion("managerLogger.f_action_res_code <>", value, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andActionResCodeGreaterThan(String value) {
            addCriterion("managerLogger.f_action_res_code >", value, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andActionResCodeGreaterThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_action_res_code >=", value, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andActionResCodeLessThan(String value) {
            addCriterion("managerLogger.f_action_res_code <", value, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andActionResCodeLessThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_action_res_code <=", value, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andActionResCodeLike(String value) {
            addCriterion("managerLogger.f_action_res_code like", value, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andActionResCodeNotLike(String value) {
            addCriterion("managerLogger.f_action_res_code not like", value, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andActionResCodeIn(List<String> values) {
            addCriterion("managerLogger.f_action_res_code in", values, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andActionResCodeNotIn(List<String> values) {
            addCriterion("managerLogger.f_action_res_code not in", values, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andActionResCodeBetween(String value1, String value2) {
            addCriterion("managerLogger.f_action_res_code between", value1, value2, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andActionResCodeNotBetween(String value1, String value2) {
            addCriterion("managerLogger.f_action_res_code not between", value1, value2, "actionResCode");
            return (Criteria) this;
        }

        public Criteria andActionResMsgIsNull() {
            addCriterion("managerLogger.f_action_res_msg is null");
            return (Criteria) this;
        }

        public Criteria andActionResMsgIsNotNull() {
            addCriterion("managerLogger.f_action_res_msg is not null");
            return (Criteria) this;
        }

        public Criteria andActionResMsgEqualTo(String value) {
            addCriterion("managerLogger.f_action_res_msg =", value, "actionResMsg");
            return (Criteria) this;
        }

        public Criteria andActionResMsgNotEqualTo(String value) {
            addCriterion("managerLogger.f_action_res_msg <>", value, "actionResMsg");
            return (Criteria) this;
        }

        public Criteria andActionResMsgGreaterThan(String value) {
            addCriterion("managerLogger.f_action_res_msg >", value, "actionResMsg");
            return (Criteria) this;
        }

        public Criteria andActionResMsgGreaterThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_action_res_msg >=", value, "actionResMsg");
            return (Criteria) this;
        }

        public Criteria andActionResMsgLessThan(String value) {
            addCriterion("managerLogger.f_action_res_msg <", value, "actionResMsg");
            return (Criteria) this;
        }

        public Criteria andActionResMsgLessThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_action_res_msg <=", value, "actionResMsg");
            return (Criteria) this;
        }

        public Criteria andActionResMsgLike(String value) {
            addCriterion("managerLogger.f_action_res_msg like", value, "actionResMsg");
            return (Criteria) this;
        }

        public Criteria andActionResMsgNotLike(String value) {
            addCriterion("managerLogger.f_action_res_msg not like", value, "actionResMsg");
            return (Criteria) this;
        }

        public Criteria andActionResMsgIn(List<String> values) {
            addCriterion("managerLogger.f_action_res_msg in", values, "actionResMsg");
            return (Criteria) this;
        }

        public Criteria andActionResMsgNotIn(List<String> values) {
            addCriterion("managerLogger.f_action_res_msg not in", values, "actionResMsg");
            return (Criteria) this;
        }

        public Criteria andActionResMsgBetween(String value1, String value2) {
            addCriterion("managerLogger.f_action_res_msg between", value1, value2, "actionResMsg");
            return (Criteria) this;
        }

        public Criteria andActionResMsgNotBetween(String value1, String value2) {
            addCriterion("managerLogger.f_action_res_msg not between", value1, value2, "actionResMsg");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionIsNull() {
            addCriterion("managerLogger.f_is_undefined_exception is null");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionIsNotNull() {
            addCriterion("managerLogger.f_is_undefined_exception is not null");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionEqualTo(Byte value) {
            addCriterion("managerLogger.f_is_undefined_exception =", value, "isUndefinedException");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionNotEqualTo(Byte value) {
            addCriterion("managerLogger.f_is_undefined_exception <>", value, "isUndefinedException");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionGreaterThan(Byte value) {
            addCriterion("managerLogger.f_is_undefined_exception >", value, "isUndefinedException");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionGreaterThanOrEqualTo(Byte value) {
            addCriterion("managerLogger.f_is_undefined_exception >=", value, "isUndefinedException");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionLessThan(Byte value) {
            addCriterion("managerLogger.f_is_undefined_exception <", value, "isUndefinedException");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionLessThanOrEqualTo(Byte value) {
            addCriterion("managerLogger.f_is_undefined_exception <=", value, "isUndefinedException");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionIn(List<Byte> values) {
            addCriterion("managerLogger.f_is_undefined_exception in", values, "isUndefinedException");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionNotIn(List<Byte> values) {
            addCriterion("managerLogger.f_is_undefined_exception not in", values, "isUndefinedException");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionBetween(Byte value1, Byte value2) {
            addCriterion("managerLogger.f_is_undefined_exception between", value1, value2, "isUndefinedException");
            return (Criteria) this;
        }

        public Criteria andIsUndefinedExceptionNotBetween(Byte value1, Byte value2) {
            addCriterion("managerLogger.f_is_undefined_exception not between", value1, value2, "isUndefinedException");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("managerLogger.f_ip is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("managerLogger.f_ip is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("managerLogger.f_ip =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("managerLogger.f_ip <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("managerLogger.f_ip >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_ip >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("managerLogger.f_ip <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_ip <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("managerLogger.f_ip like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("managerLogger.f_ip not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("managerLogger.f_ip in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("managerLogger.f_ip not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("managerLogger.f_ip between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("managerLogger.f_ip not between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNull() {
            addCriterion("managerLogger.f_device_id is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNotNull() {
            addCriterion("managerLogger.f_device_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdEqualTo(String value) {
            addCriterion("managerLogger.f_device_id =", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotEqualTo(String value) {
            addCriterion("managerLogger.f_device_id <>", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThan(String value) {
            addCriterion("managerLogger.f_device_id >", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_device_id >=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThan(String value) {
            addCriterion("managerLogger.f_device_id <", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_device_id <=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLike(String value) {
            addCriterion("managerLogger.f_device_id like", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotLike(String value) {
            addCriterion("managerLogger.f_device_id not like", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIn(List<String> values) {
            addCriterion("managerLogger.f_device_id in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotIn(List<String> values) {
            addCriterion("managerLogger.f_device_id not in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdBetween(String value1, String value2) {
            addCriterion("managerLogger.f_device_id between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotBetween(String value1, String value2) {
            addCriterion("managerLogger.f_device_id not between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andOsVerIsNull() {
            addCriterion("managerLogger.f_os_ver is null");
            return (Criteria) this;
        }

        public Criteria andOsVerIsNotNull() {
            addCriterion("managerLogger.f_os_ver is not null");
            return (Criteria) this;
        }

        public Criteria andOsVerEqualTo(String value) {
            addCriterion("managerLogger.f_os_ver =", value, "osVer");
            return (Criteria) this;
        }

        public Criteria andOsVerNotEqualTo(String value) {
            addCriterion("managerLogger.f_os_ver <>", value, "osVer");
            return (Criteria) this;
        }

        public Criteria andOsVerGreaterThan(String value) {
            addCriterion("managerLogger.f_os_ver >", value, "osVer");
            return (Criteria) this;
        }

        public Criteria andOsVerGreaterThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_os_ver >=", value, "osVer");
            return (Criteria) this;
        }

        public Criteria andOsVerLessThan(String value) {
            addCriterion("managerLogger.f_os_ver <", value, "osVer");
            return (Criteria) this;
        }

        public Criteria andOsVerLessThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_os_ver <=", value, "osVer");
            return (Criteria) this;
        }

        public Criteria andOsVerLike(String value) {
            addCriterion("managerLogger.f_os_ver like", value, "osVer");
            return (Criteria) this;
        }

        public Criteria andOsVerNotLike(String value) {
            addCriterion("managerLogger.f_os_ver not like", value, "osVer");
            return (Criteria) this;
        }

        public Criteria andOsVerIn(List<String> values) {
            addCriterion("managerLogger.f_os_ver in", values, "osVer");
            return (Criteria) this;
        }

        public Criteria andOsVerNotIn(List<String> values) {
            addCriterion("managerLogger.f_os_ver not in", values, "osVer");
            return (Criteria) this;
        }

        public Criteria andOsVerBetween(String value1, String value2) {
            addCriterion("managerLogger.f_os_ver between", value1, value2, "osVer");
            return (Criteria) this;
        }

        public Criteria andOsVerNotBetween(String value1, String value2) {
            addCriterion("managerLogger.f_os_ver not between", value1, value2, "osVer");
            return (Criteria) this;
        }

        public Criteria andCommSysUrlFIdIsNull() {
            addCriterion("managerLogger.t_comm_sys_url_f_id is null");
            return (Criteria) this;
        }

        public Criteria andCommSysUrlFIdIsNotNull() {
            addCriterion("managerLogger.t_comm_sys_url_f_id is not null");
            return (Criteria) this;
        }

        public Criteria andCommSysUrlFIdEqualTo(Long value) {
            addCriterion("managerLogger.t_comm_sys_url_f_id =", value, "commSysUrlFId");
            return (Criteria) this;
        }

        public Criteria andCommSysUrlFIdNotEqualTo(Long value) {
            addCriterion("managerLogger.t_comm_sys_url_f_id <>", value, "commSysUrlFId");
            return (Criteria) this;
        }

        public Criteria andCommSysUrlFIdGreaterThan(Long value) {
            addCriterion("managerLogger.t_comm_sys_url_f_id >", value, "commSysUrlFId");
            return (Criteria) this;
        }

        public Criteria andCommSysUrlFIdGreaterThanOrEqualTo(Long value) {
            addCriterion("managerLogger.t_comm_sys_url_f_id >=", value, "commSysUrlFId");
            return (Criteria) this;
        }

        public Criteria andCommSysUrlFIdLessThan(Long value) {
            addCriterion("managerLogger.t_comm_sys_url_f_id <", value, "commSysUrlFId");
            return (Criteria) this;
        }

        public Criteria andCommSysUrlFIdLessThanOrEqualTo(Long value) {
            addCriterion("managerLogger.t_comm_sys_url_f_id <=", value, "commSysUrlFId");
            return (Criteria) this;
        }

        public Criteria andCommSysUrlFIdIn(List<Long> values) {
            addCriterion("managerLogger.t_comm_sys_url_f_id in", values, "commSysUrlFId");
            return (Criteria) this;
        }

        public Criteria andCommSysUrlFIdNotIn(List<Long> values) {
            addCriterion("managerLogger.t_comm_sys_url_f_id not in", values, "commSysUrlFId");
            return (Criteria) this;
        }

        public Criteria andCommSysUrlFIdBetween(Long value1, Long value2) {
            addCriterion("managerLogger.t_comm_sys_url_f_id between", value1, value2, "commSysUrlFId");
            return (Criteria) this;
        }

        public Criteria andCommSysUrlFIdNotBetween(Long value1, Long value2) {
            addCriterion("managerLogger.t_comm_sys_url_f_id not between", value1, value2, "commSysUrlFId");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeIsNull() {
            addCriterion("managerLogger.f_req_deal_time is null");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeIsNotNull() {
            addCriterion("managerLogger.f_req_deal_time is not null");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeEqualTo(Integer value) {
            addCriterion("managerLogger.f_req_deal_time =", value, "reqDealTime");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeNotEqualTo(Integer value) {
            addCriterion("managerLogger.f_req_deal_time <>", value, "reqDealTime");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeGreaterThan(Integer value) {
            addCriterion("managerLogger.f_req_deal_time >", value, "reqDealTime");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("managerLogger.f_req_deal_time >=", value, "reqDealTime");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeLessThan(Integer value) {
            addCriterion("managerLogger.f_req_deal_time <", value, "reqDealTime");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeLessThanOrEqualTo(Integer value) {
            addCriterion("managerLogger.f_req_deal_time <=", value, "reqDealTime");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeIn(List<Integer> values) {
            addCriterion("managerLogger.f_req_deal_time in", values, "reqDealTime");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeNotIn(List<Integer> values) {
            addCriterion("managerLogger.f_req_deal_time not in", values, "reqDealTime");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeBetween(Integer value1, Integer value2) {
            addCriterion("managerLogger.f_req_deal_time between", value1, value2, "reqDealTime");
            return (Criteria) this;
        }

        public Criteria andReqDealTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("managerLogger.f_req_deal_time not between", value1, value2, "reqDealTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeIsNull() {
            addCriterion("managerLogger.f_req_end_time is null");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeIsNotNull() {
            addCriterion("managerLogger.f_req_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeEqualTo(Date value) {
            addCriterion("managerLogger.f_req_end_time =", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeNotEqualTo(Date value) {
            addCriterion("managerLogger.f_req_end_time <>", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeGreaterThan(Date value) {
            addCriterion("managerLogger.f_req_end_time >", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("managerLogger.f_req_end_time >=", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeLessThan(Date value) {
            addCriterion("managerLogger.f_req_end_time <", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("managerLogger.f_req_end_time <=", value, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeIn(List<Date> values) {
            addCriterion("managerLogger.f_req_end_time in", values, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeNotIn(List<Date> values) {
            addCriterion("managerLogger.f_req_end_time not in", values, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeBetween(Date value1, Date value2) {
            addCriterion("managerLogger.f_req_end_time between", value1, value2, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andReqEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("managerLogger.f_req_end_time not between", value1, value2, "reqEndTime");
            return (Criteria) this;
        }

        public Criteria andTransNoIsNull() {
            addCriterion("managerLogger.f_trans_no is null");
            return (Criteria) this;
        }

        public Criteria andTransNoIsNotNull() {
            addCriterion("managerLogger.f_trans_no is not null");
            return (Criteria) this;
        }

        public Criteria andTransNoEqualTo(String value) {
            addCriterion("managerLogger.f_trans_no =", value, "transNo");
            return (Criteria) this;
        }

        public Criteria andTransNoNotEqualTo(String value) {
            addCriterion("managerLogger.f_trans_no <>", value, "transNo");
            return (Criteria) this;
        }

        public Criteria andTransNoGreaterThan(String value) {
            addCriterion("managerLogger.f_trans_no >", value, "transNo");
            return (Criteria) this;
        }

        public Criteria andTransNoGreaterThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_trans_no >=", value, "transNo");
            return (Criteria) this;
        }

        public Criteria andTransNoLessThan(String value) {
            addCriterion("managerLogger.f_trans_no <", value, "transNo");
            return (Criteria) this;
        }

        public Criteria andTransNoLessThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_trans_no <=", value, "transNo");
            return (Criteria) this;
        }

        public Criteria andTransNoLike(String value) {
            addCriterion("managerLogger.f_trans_no like", value, "transNo");
            return (Criteria) this;
        }

        public Criteria andTransNoNotLike(String value) {
            addCriterion("managerLogger.f_trans_no not like", value, "transNo");
            return (Criteria) this;
        }

        public Criteria andTransNoIn(List<String> values) {
            addCriterion("managerLogger.f_trans_no in", values, "transNo");
            return (Criteria) this;
        }

        public Criteria andTransNoNotIn(List<String> values) {
            addCriterion("managerLogger.f_trans_no not in", values, "transNo");
            return (Criteria) this;
        }

        public Criteria andTransNoBetween(String value1, String value2) {
            addCriterion("managerLogger.f_trans_no between", value1, value2, "transNo");
            return (Criteria) this;
        }

        public Criteria andTransNoNotBetween(String value1, String value2) {
            addCriterion("managerLogger.f_trans_no not between", value1, value2, "transNo");
            return (Criteria) this;
        }

        public Criteria andChannelIsNull() {
            addCriterion("managerLogger.f_channel is null");
            return (Criteria) this;
        }

        public Criteria andChannelIsNotNull() {
            addCriterion("managerLogger.f_channel is not null");
            return (Criteria) this;
        }

        public Criteria andChannelEqualTo(String value) {
            addCriterion("managerLogger.f_channel =", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotEqualTo(String value) {
            addCriterion("managerLogger.f_channel <>", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThan(String value) {
            addCriterion("managerLogger.f_channel >", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_channel >=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThan(String value) {
            addCriterion("managerLogger.f_channel <", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_channel <=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLike(String value) {
            addCriterion("managerLogger.f_channel like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotLike(String value) {
            addCriterion("managerLogger.f_channel not like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelIn(List<String> values) {
            addCriterion("managerLogger.f_channel in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotIn(List<String> values) {
            addCriterion("managerLogger.f_channel not in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelBetween(String value1, String value2) {
            addCriterion("managerLogger.f_channel between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotBetween(String value1, String value2) {
            addCriterion("managerLogger.f_channel not between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("managerLogger.f_version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("managerLogger.f_version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("managerLogger.f_version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("managerLogger.f_version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("managerLogger.f_version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("managerLogger.f_version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("managerLogger.f_version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("managerLogger.f_version like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("managerLogger.f_version not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("managerLogger.f_version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("managerLogger.f_version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("managerLogger.f_version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("managerLogger.f_version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeIsNull() {
            addCriterion("managerLogger.f_sys0_add_time is null");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeIsNotNull() {
            addCriterion("managerLogger.f_sys0_add_time is not null");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeEqualTo(Date value) {
            addCriterion("managerLogger.f_sys0_add_time =", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeNotEqualTo(Date value) {
            addCriterion("managerLogger.f_sys0_add_time <>", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeGreaterThan(Date value) {
            addCriterion("managerLogger.f_sys0_add_time >", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("managerLogger.f_sys0_add_time >=", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeLessThan(Date value) {
            addCriterion("managerLogger.f_sys0_add_time <", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeLessThanOrEqualTo(Date value) {
            addCriterion("managerLogger.f_sys0_add_time <=", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeIn(List<Date> values) {
            addCriterion("managerLogger.f_sys0_add_time in", values, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeNotIn(List<Date> values) {
            addCriterion("managerLogger.f_sys0_add_time not in", values, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeBetween(Date value1, Date value2) {
            addCriterion("managerLogger.f_sys0_add_time between", value1, value2, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeNotBetween(Date value1, Date value2) {
            addCriterion("managerLogger.f_sys0_add_time not between", value1, value2, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeIsNull() {
            addCriterion("managerLogger.f_sys0_upd_time is null");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeIsNotNull() {
            addCriterion("managerLogger.f_sys0_upd_time is not null");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeEqualTo(Date value) {
            addCriterion("managerLogger.f_sys0_upd_time =", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeNotEqualTo(Date value) {
            addCriterion("managerLogger.f_sys0_upd_time <>", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeGreaterThan(Date value) {
            addCriterion("managerLogger.f_sys0_upd_time >", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("managerLogger.f_sys0_upd_time >=", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeLessThan(Date value) {
            addCriterion("managerLogger.f_sys0_upd_time <", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeLessThanOrEqualTo(Date value) {
            addCriterion("managerLogger.f_sys0_upd_time <=", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeIn(List<Date> values) {
            addCriterion("managerLogger.f_sys0_upd_time in", values, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeNotIn(List<Date> values) {
            addCriterion("managerLogger.f_sys0_upd_time not in", values, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeBetween(Date value1, Date value2) {
            addCriterion("managerLogger.f_sys0_upd_time between", value1, value2, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeNotBetween(Date value1, Date value2) {
            addCriterion("managerLogger.f_sys0_upd_time not between", value1, value2, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeIsNull() {
            addCriterion("managerLogger.f_sys0_del_time is null");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeIsNotNull() {
            addCriterion("managerLogger.f_sys0_del_time is not null");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeEqualTo(Date value) {
            addCriterion("managerLogger.f_sys0_del_time =", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeNotEqualTo(Date value) {
            addCriterion("managerLogger.f_sys0_del_time <>", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeGreaterThan(Date value) {
            addCriterion("managerLogger.f_sys0_del_time >", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("managerLogger.f_sys0_del_time >=", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeLessThan(Date value) {
            addCriterion("managerLogger.f_sys0_del_time <", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeLessThanOrEqualTo(Date value) {
            addCriterion("managerLogger.f_sys0_del_time <=", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeIn(List<Date> values) {
            addCriterion("managerLogger.f_sys0_del_time in", values, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeNotIn(List<Date> values) {
            addCriterion("managerLogger.f_sys0_del_time not in", values, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeBetween(Date value1, Date value2) {
            addCriterion("managerLogger.f_sys0_del_time between", value1, value2, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeNotBetween(Date value1, Date value2) {
            addCriterion("managerLogger.f_sys0_del_time not between", value1, value2, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserIsNull() {
            addCriterion("managerLogger.f_sys0_add_user is null");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserIsNotNull() {
            addCriterion("managerLogger.f_sys0_add_user is not null");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserEqualTo(Long value) {
            addCriterion("managerLogger.f_sys0_add_user =", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserNotEqualTo(Long value) {
            addCriterion("managerLogger.f_sys0_add_user <>", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserGreaterThan(Long value) {
            addCriterion("managerLogger.f_sys0_add_user >", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserGreaterThanOrEqualTo(Long value) {
            addCriterion("managerLogger.f_sys0_add_user >=", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserLessThan(Long value) {
            addCriterion("managerLogger.f_sys0_add_user <", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserLessThanOrEqualTo(Long value) {
            addCriterion("managerLogger.f_sys0_add_user <=", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserIn(List<Long> values) {
            addCriterion("managerLogger.f_sys0_add_user in", values, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserNotIn(List<Long> values) {
            addCriterion("managerLogger.f_sys0_add_user not in", values, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserBetween(Long value1, Long value2) {
            addCriterion("managerLogger.f_sys0_add_user between", value1, value2, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserNotBetween(Long value1, Long value2) {
            addCriterion("managerLogger.f_sys0_add_user not between", value1, value2, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserIsNull() {
            addCriterion("managerLogger.f_sys0_upd_user is null");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserIsNotNull() {
            addCriterion("managerLogger.f_sys0_upd_user is not null");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserEqualTo(Long value) {
            addCriterion("managerLogger.f_sys0_upd_user =", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserNotEqualTo(Long value) {
            addCriterion("managerLogger.f_sys0_upd_user <>", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserGreaterThan(Long value) {
            addCriterion("managerLogger.f_sys0_upd_user >", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserGreaterThanOrEqualTo(Long value) {
            addCriterion("managerLogger.f_sys0_upd_user >=", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserLessThan(Long value) {
            addCriterion("managerLogger.f_sys0_upd_user <", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserLessThanOrEqualTo(Long value) {
            addCriterion("managerLogger.f_sys0_upd_user <=", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserIn(List<Long> values) {
            addCriterion("managerLogger.f_sys0_upd_user in", values, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserNotIn(List<Long> values) {
            addCriterion("managerLogger.f_sys0_upd_user not in", values, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserBetween(Long value1, Long value2) {
            addCriterion("managerLogger.f_sys0_upd_user between", value1, value2, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserNotBetween(Long value1, Long value2) {
            addCriterion("managerLogger.f_sys0_upd_user not between", value1, value2, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserIsNull() {
            addCriterion("managerLogger.f_sys0_del_user is null");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserIsNotNull() {
            addCriterion("managerLogger.f_sys0_del_user is not null");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserEqualTo(Long value) {
            addCriterion("managerLogger.f_sys0_del_user =", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserNotEqualTo(Long value) {
            addCriterion("managerLogger.f_sys0_del_user <>", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserGreaterThan(Long value) {
            addCriterion("managerLogger.f_sys0_del_user >", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserGreaterThanOrEqualTo(Long value) {
            addCriterion("managerLogger.f_sys0_del_user >=", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserLessThan(Long value) {
            addCriterion("managerLogger.f_sys0_del_user <", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserLessThanOrEqualTo(Long value) {
            addCriterion("managerLogger.f_sys0_del_user <=", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserIn(List<Long> values) {
            addCriterion("managerLogger.f_sys0_del_user in", values, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserNotIn(List<Long> values) {
            addCriterion("managerLogger.f_sys0_del_user not in", values, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserBetween(Long value1, Long value2) {
            addCriterion("managerLogger.f_sys0_del_user between", value1, value2, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserNotBetween(Long value1, Long value2) {
            addCriterion("managerLogger.f_sys0_del_user not between", value1, value2, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateIsNull() {
            addCriterion("managerLogger.f_sys0_del_state is null");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateIsNotNull() {
            addCriterion("managerLogger.f_sys0_del_state is not null");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateEqualTo(Byte value) {
            addCriterion("managerLogger.f_sys0_del_state =", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateNotEqualTo(Byte value) {
            addCriterion("managerLogger.f_sys0_del_state <>", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateGreaterThan(Byte value) {
            addCriterion("managerLogger.f_sys0_del_state >", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("managerLogger.f_sys0_del_state >=", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateLessThan(Byte value) {
            addCriterion("managerLogger.f_sys0_del_state <", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateLessThanOrEqualTo(Byte value) {
            addCriterion("managerLogger.f_sys0_del_state <=", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateIn(List<Byte> values) {
            addCriterion("managerLogger.f_sys0_del_state in", values, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateNotIn(List<Byte> values) {
            addCriterion("managerLogger.f_sys0_del_state not in", values, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateBetween(Byte value1, Byte value2) {
            addCriterion("managerLogger.f_sys0_del_state between", value1, value2, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateNotBetween(Byte value1, Byte value2) {
            addCriterion("managerLogger.f_sys0_del_state not between", value1, value2, "sys0DelState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_manager_logger
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_manager_logger
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}