package org.prcode.business.basedomain.omsCommSysPara.domain;

import java.util.Date;
import org.prcode.basedomain.base.BaseDomain;

public class OmsCommSysPara extends BaseDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oms_comm_sys_para.f_id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oms_comm_sys_para.f_sys_para_code
     *
     * @mbg.generated
     */
    private String sysParaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oms_comm_sys_para.f_sys_para_value
     *
     * @mbg.generated
     */
    private String sysParaValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oms_comm_sys_para.f_sys_para_desc
     *
     * @mbg.generated
     */
    private String sysParaDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oms_comm_sys_para.f_sys0_del_time
     *
     * @mbg.generated
     */
    private Date sys0DelTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oms_comm_sys_para.f_sys0_del_state
     *
     * @mbg.generated
     */
    private Byte sys0DelState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oms_comm_sys_para.f_id
     *
     * @return the value of t_oms_comm_sys_para.f_id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oms_comm_sys_para.f_id
     *
     * @param id the value for t_oms_comm_sys_para.f_id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oms_comm_sys_para.f_sys_para_code
     *
     * @return the value of t_oms_comm_sys_para.f_sys_para_code
     *
     * @mbg.generated
     */
    public String getSysParaCode() {
        return sysParaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oms_comm_sys_para.f_sys_para_code
     *
     * @param sysParaCode the value for t_oms_comm_sys_para.f_sys_para_code
     *
     * @mbg.generated
     */
    public void setSysParaCode(String sysParaCode) {
        this.sysParaCode = sysParaCode == null ? null : sysParaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oms_comm_sys_para.f_sys_para_value
     *
     * @return the value of t_oms_comm_sys_para.f_sys_para_value
     *
     * @mbg.generated
     */
    public String getSysParaValue() {
        return sysParaValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oms_comm_sys_para.f_sys_para_value
     *
     * @param sysParaValue the value for t_oms_comm_sys_para.f_sys_para_value
     *
     * @mbg.generated
     */
    public void setSysParaValue(String sysParaValue) {
        this.sysParaValue = sysParaValue == null ? null : sysParaValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oms_comm_sys_para.f_sys_para_desc
     *
     * @return the value of t_oms_comm_sys_para.f_sys_para_desc
     *
     * @mbg.generated
     */
    public String getSysParaDesc() {
        return sysParaDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oms_comm_sys_para.f_sys_para_desc
     *
     * @param sysParaDesc the value for t_oms_comm_sys_para.f_sys_para_desc
     *
     * @mbg.generated
     */
    public void setSysParaDesc(String sysParaDesc) {
        this.sysParaDesc = sysParaDesc == null ? null : sysParaDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oms_comm_sys_para.f_sys0_del_time
     *
     * @return the value of t_oms_comm_sys_para.f_sys0_del_time
     *
     * @mbg.generated
     */
    public Date getSys0DelTime() {
        return sys0DelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oms_comm_sys_para.f_sys0_del_time
     *
     * @param sys0DelTime the value for t_oms_comm_sys_para.f_sys0_del_time
     *
     * @mbg.generated
     */
    public void setSys0DelTime(Date sys0DelTime) {
        this.sys0DelTime = sys0DelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oms_comm_sys_para.f_sys0_del_state
     *
     * @return the value of t_oms_comm_sys_para.f_sys0_del_state
     *
     * @mbg.generated
     */
    public Byte getSys0DelState() {
        return sys0DelState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oms_comm_sys_para.f_sys0_del_state
     *
     * @param sys0DelState the value for t_oms_comm_sys_para.f_sys0_del_state
     *
     * @mbg.generated
     */
    public void setSys0DelState(Byte sys0DelState) {
        this.sys0DelState = sys0DelState;
    }
}