package org.prcode.business.basedomain.omsCommSysPara.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OmsCommSysParaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_oms_comm_sys_para
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_oms_comm_sys_para
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_oms_comm_sys_para
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oms_comm_sys_para
     *
     * @mbg.generated
     */
    public OmsCommSysParaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oms_comm_sys_para
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oms_comm_sys_para
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oms_comm_sys_para
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oms_comm_sys_para
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oms_comm_sys_para
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oms_comm_sys_para
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oms_comm_sys_para
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oms_comm_sys_para
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oms_comm_sys_para
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oms_comm_sys_para
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_oms_comm_sys_para
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("omsCommSysPara.f_id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("omsCommSysPara.f_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("omsCommSysPara.f_id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("omsCommSysPara.f_id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("omsCommSysPara.f_id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("omsCommSysPara.f_id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("omsCommSysPara.f_id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("omsCommSysPara.f_id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("omsCommSysPara.f_id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("omsCommSysPara.f_id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("omsCommSysPara.f_id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("omsCommSysPara.f_id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSysParaCodeIsNull() {
            addCriterion("omsCommSysPara.f_sys_para_code is null");
            return (Criteria) this;
        }

        public Criteria andSysParaCodeIsNotNull() {
            addCriterion("omsCommSysPara.f_sys_para_code is not null");
            return (Criteria) this;
        }

        public Criteria andSysParaCodeEqualTo(String value) {
            addCriterion("omsCommSysPara.f_sys_para_code =", value, "sysParaCode");
            return (Criteria) this;
        }

        public Criteria andSysParaCodeNotEqualTo(String value) {
            addCriterion("omsCommSysPara.f_sys_para_code <>", value, "sysParaCode");
            return (Criteria) this;
        }

        public Criteria andSysParaCodeGreaterThan(String value) {
            addCriterion("omsCommSysPara.f_sys_para_code >", value, "sysParaCode");
            return (Criteria) this;
        }

        public Criteria andSysParaCodeGreaterThanOrEqualTo(String value) {
            addCriterion("omsCommSysPara.f_sys_para_code >=", value, "sysParaCode");
            return (Criteria) this;
        }

        public Criteria andSysParaCodeLessThan(String value) {
            addCriterion("omsCommSysPara.f_sys_para_code <", value, "sysParaCode");
            return (Criteria) this;
        }

        public Criteria andSysParaCodeLessThanOrEqualTo(String value) {
            addCriterion("omsCommSysPara.f_sys_para_code <=", value, "sysParaCode");
            return (Criteria) this;
        }

        public Criteria andSysParaCodeLike(String value) {
            addCriterion("omsCommSysPara.f_sys_para_code like", value, "sysParaCode");
            return (Criteria) this;
        }

        public Criteria andSysParaCodeNotLike(String value) {
            addCriterion("omsCommSysPara.f_sys_para_code not like", value, "sysParaCode");
            return (Criteria) this;
        }

        public Criteria andSysParaCodeIn(List<String> values) {
            addCriterion("omsCommSysPara.f_sys_para_code in", values, "sysParaCode");
            return (Criteria) this;
        }

        public Criteria andSysParaCodeNotIn(List<String> values) {
            addCriterion("omsCommSysPara.f_sys_para_code not in", values, "sysParaCode");
            return (Criteria) this;
        }

        public Criteria andSysParaCodeBetween(String value1, String value2) {
            addCriterion("omsCommSysPara.f_sys_para_code between", value1, value2, "sysParaCode");
            return (Criteria) this;
        }

        public Criteria andSysParaCodeNotBetween(String value1, String value2) {
            addCriterion("omsCommSysPara.f_sys_para_code not between", value1, value2, "sysParaCode");
            return (Criteria) this;
        }

        public Criteria andSysParaValueIsNull() {
            addCriterion("omsCommSysPara.f_sys_para_value is null");
            return (Criteria) this;
        }

        public Criteria andSysParaValueIsNotNull() {
            addCriterion("omsCommSysPara.f_sys_para_value is not null");
            return (Criteria) this;
        }

        public Criteria andSysParaValueEqualTo(String value) {
            addCriterion("omsCommSysPara.f_sys_para_value =", value, "sysParaValue");
            return (Criteria) this;
        }

        public Criteria andSysParaValueNotEqualTo(String value) {
            addCriterion("omsCommSysPara.f_sys_para_value <>", value, "sysParaValue");
            return (Criteria) this;
        }

        public Criteria andSysParaValueGreaterThan(String value) {
            addCriterion("omsCommSysPara.f_sys_para_value >", value, "sysParaValue");
            return (Criteria) this;
        }

        public Criteria andSysParaValueGreaterThanOrEqualTo(String value) {
            addCriterion("omsCommSysPara.f_sys_para_value >=", value, "sysParaValue");
            return (Criteria) this;
        }

        public Criteria andSysParaValueLessThan(String value) {
            addCriterion("omsCommSysPara.f_sys_para_value <", value, "sysParaValue");
            return (Criteria) this;
        }

        public Criteria andSysParaValueLessThanOrEqualTo(String value) {
            addCriterion("omsCommSysPara.f_sys_para_value <=", value, "sysParaValue");
            return (Criteria) this;
        }

        public Criteria andSysParaValueLike(String value) {
            addCriterion("omsCommSysPara.f_sys_para_value like", value, "sysParaValue");
            return (Criteria) this;
        }

        public Criteria andSysParaValueNotLike(String value) {
            addCriterion("omsCommSysPara.f_sys_para_value not like", value, "sysParaValue");
            return (Criteria) this;
        }

        public Criteria andSysParaValueIn(List<String> values) {
            addCriterion("omsCommSysPara.f_sys_para_value in", values, "sysParaValue");
            return (Criteria) this;
        }

        public Criteria andSysParaValueNotIn(List<String> values) {
            addCriterion("omsCommSysPara.f_sys_para_value not in", values, "sysParaValue");
            return (Criteria) this;
        }

        public Criteria andSysParaValueBetween(String value1, String value2) {
            addCriterion("omsCommSysPara.f_sys_para_value between", value1, value2, "sysParaValue");
            return (Criteria) this;
        }

        public Criteria andSysParaValueNotBetween(String value1, String value2) {
            addCriterion("omsCommSysPara.f_sys_para_value not between", value1, value2, "sysParaValue");
            return (Criteria) this;
        }

        public Criteria andSysParaDescIsNull() {
            addCriterion("omsCommSysPara.f_sys_para_desc is null");
            return (Criteria) this;
        }

        public Criteria andSysParaDescIsNotNull() {
            addCriterion("omsCommSysPara.f_sys_para_desc is not null");
            return (Criteria) this;
        }

        public Criteria andSysParaDescEqualTo(String value) {
            addCriterion("omsCommSysPara.f_sys_para_desc =", value, "sysParaDesc");
            return (Criteria) this;
        }

        public Criteria andSysParaDescNotEqualTo(String value) {
            addCriterion("omsCommSysPara.f_sys_para_desc <>", value, "sysParaDesc");
            return (Criteria) this;
        }

        public Criteria andSysParaDescGreaterThan(String value) {
            addCriterion("omsCommSysPara.f_sys_para_desc >", value, "sysParaDesc");
            return (Criteria) this;
        }

        public Criteria andSysParaDescGreaterThanOrEqualTo(String value) {
            addCriterion("omsCommSysPara.f_sys_para_desc >=", value, "sysParaDesc");
            return (Criteria) this;
        }

        public Criteria andSysParaDescLessThan(String value) {
            addCriterion("omsCommSysPara.f_sys_para_desc <", value, "sysParaDesc");
            return (Criteria) this;
        }

        public Criteria andSysParaDescLessThanOrEqualTo(String value) {
            addCriterion("omsCommSysPara.f_sys_para_desc <=", value, "sysParaDesc");
            return (Criteria) this;
        }

        public Criteria andSysParaDescLike(String value) {
            addCriterion("omsCommSysPara.f_sys_para_desc like", value, "sysParaDesc");
            return (Criteria) this;
        }

        public Criteria andSysParaDescNotLike(String value) {
            addCriterion("omsCommSysPara.f_sys_para_desc not like", value, "sysParaDesc");
            return (Criteria) this;
        }

        public Criteria andSysParaDescIn(List<String> values) {
            addCriterion("omsCommSysPara.f_sys_para_desc in", values, "sysParaDesc");
            return (Criteria) this;
        }

        public Criteria andSysParaDescNotIn(List<String> values) {
            addCriterion("omsCommSysPara.f_sys_para_desc not in", values, "sysParaDesc");
            return (Criteria) this;
        }

        public Criteria andSysParaDescBetween(String value1, String value2) {
            addCriterion("omsCommSysPara.f_sys_para_desc between", value1, value2, "sysParaDesc");
            return (Criteria) this;
        }

        public Criteria andSysParaDescNotBetween(String value1, String value2) {
            addCriterion("omsCommSysPara.f_sys_para_desc not between", value1, value2, "sysParaDesc");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeIsNull() {
            addCriterion("omsCommSysPara.f_sys0_add_time is null");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeIsNotNull() {
            addCriterion("omsCommSysPara.f_sys0_add_time is not null");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeEqualTo(Date value) {
            addCriterion("omsCommSysPara.f_sys0_add_time =", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeNotEqualTo(Date value) {
            addCriterion("omsCommSysPara.f_sys0_add_time <>", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeGreaterThan(Date value) {
            addCriterion("omsCommSysPara.f_sys0_add_time >", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("omsCommSysPara.f_sys0_add_time >=", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeLessThan(Date value) {
            addCriterion("omsCommSysPara.f_sys0_add_time <", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeLessThanOrEqualTo(Date value) {
            addCriterion("omsCommSysPara.f_sys0_add_time <=", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeIn(List<Date> values) {
            addCriterion("omsCommSysPara.f_sys0_add_time in", values, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeNotIn(List<Date> values) {
            addCriterion("omsCommSysPara.f_sys0_add_time not in", values, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeBetween(Date value1, Date value2) {
            addCriterion("omsCommSysPara.f_sys0_add_time between", value1, value2, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeNotBetween(Date value1, Date value2) {
            addCriterion("omsCommSysPara.f_sys0_add_time not between", value1, value2, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeIsNull() {
            addCriterion("omsCommSysPara.f_sys0_upd_time is null");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeIsNotNull() {
            addCriterion("omsCommSysPara.f_sys0_upd_time is not null");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeEqualTo(Date value) {
            addCriterion("omsCommSysPara.f_sys0_upd_time =", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeNotEqualTo(Date value) {
            addCriterion("omsCommSysPara.f_sys0_upd_time <>", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeGreaterThan(Date value) {
            addCriterion("omsCommSysPara.f_sys0_upd_time >", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("omsCommSysPara.f_sys0_upd_time >=", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeLessThan(Date value) {
            addCriterion("omsCommSysPara.f_sys0_upd_time <", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeLessThanOrEqualTo(Date value) {
            addCriterion("omsCommSysPara.f_sys0_upd_time <=", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeIn(List<Date> values) {
            addCriterion("omsCommSysPara.f_sys0_upd_time in", values, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeNotIn(List<Date> values) {
            addCriterion("omsCommSysPara.f_sys0_upd_time not in", values, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeBetween(Date value1, Date value2) {
            addCriterion("omsCommSysPara.f_sys0_upd_time between", value1, value2, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeNotBetween(Date value1, Date value2) {
            addCriterion("omsCommSysPara.f_sys0_upd_time not between", value1, value2, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeIsNull() {
            addCriterion("omsCommSysPara.f_sys0_del_time is null");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeIsNotNull() {
            addCriterion("omsCommSysPara.f_sys0_del_time is not null");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeEqualTo(Date value) {
            addCriterion("omsCommSysPara.f_sys0_del_time =", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeNotEqualTo(Date value) {
            addCriterion("omsCommSysPara.f_sys0_del_time <>", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeGreaterThan(Date value) {
            addCriterion("omsCommSysPara.f_sys0_del_time >", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("omsCommSysPara.f_sys0_del_time >=", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeLessThan(Date value) {
            addCriterion("omsCommSysPara.f_sys0_del_time <", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeLessThanOrEqualTo(Date value) {
            addCriterion("omsCommSysPara.f_sys0_del_time <=", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeIn(List<Date> values) {
            addCriterion("omsCommSysPara.f_sys0_del_time in", values, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeNotIn(List<Date> values) {
            addCriterion("omsCommSysPara.f_sys0_del_time not in", values, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeBetween(Date value1, Date value2) {
            addCriterion("omsCommSysPara.f_sys0_del_time between", value1, value2, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeNotBetween(Date value1, Date value2) {
            addCriterion("omsCommSysPara.f_sys0_del_time not between", value1, value2, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserIsNull() {
            addCriterion("omsCommSysPara.f_sys0_add_user is null");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserIsNotNull() {
            addCriterion("omsCommSysPara.f_sys0_add_user is not null");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserEqualTo(Long value) {
            addCriterion("omsCommSysPara.f_sys0_add_user =", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserNotEqualTo(Long value) {
            addCriterion("omsCommSysPara.f_sys0_add_user <>", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserGreaterThan(Long value) {
            addCriterion("omsCommSysPara.f_sys0_add_user >", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserGreaterThanOrEqualTo(Long value) {
            addCriterion("omsCommSysPara.f_sys0_add_user >=", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserLessThan(Long value) {
            addCriterion("omsCommSysPara.f_sys0_add_user <", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserLessThanOrEqualTo(Long value) {
            addCriterion("omsCommSysPara.f_sys0_add_user <=", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserIn(List<Long> values) {
            addCriterion("omsCommSysPara.f_sys0_add_user in", values, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserNotIn(List<Long> values) {
            addCriterion("omsCommSysPara.f_sys0_add_user not in", values, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserBetween(Long value1, Long value2) {
            addCriterion("omsCommSysPara.f_sys0_add_user between", value1, value2, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserNotBetween(Long value1, Long value2) {
            addCriterion("omsCommSysPara.f_sys0_add_user not between", value1, value2, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserIsNull() {
            addCriterion("omsCommSysPara.f_sys0_upd_user is null");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserIsNotNull() {
            addCriterion("omsCommSysPara.f_sys0_upd_user is not null");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserEqualTo(Long value) {
            addCriterion("omsCommSysPara.f_sys0_upd_user =", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserNotEqualTo(Long value) {
            addCriterion("omsCommSysPara.f_sys0_upd_user <>", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserGreaterThan(Long value) {
            addCriterion("omsCommSysPara.f_sys0_upd_user >", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserGreaterThanOrEqualTo(Long value) {
            addCriterion("omsCommSysPara.f_sys0_upd_user >=", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserLessThan(Long value) {
            addCriterion("omsCommSysPara.f_sys0_upd_user <", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserLessThanOrEqualTo(Long value) {
            addCriterion("omsCommSysPara.f_sys0_upd_user <=", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserIn(List<Long> values) {
            addCriterion("omsCommSysPara.f_sys0_upd_user in", values, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserNotIn(List<Long> values) {
            addCriterion("omsCommSysPara.f_sys0_upd_user not in", values, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserBetween(Long value1, Long value2) {
            addCriterion("omsCommSysPara.f_sys0_upd_user between", value1, value2, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserNotBetween(Long value1, Long value2) {
            addCriterion("omsCommSysPara.f_sys0_upd_user not between", value1, value2, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserIsNull() {
            addCriterion("omsCommSysPara.f_sys0_del_user is null");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserIsNotNull() {
            addCriterion("omsCommSysPara.f_sys0_del_user is not null");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserEqualTo(Long value) {
            addCriterion("omsCommSysPara.f_sys0_del_user =", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserNotEqualTo(Long value) {
            addCriterion("omsCommSysPara.f_sys0_del_user <>", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserGreaterThan(Long value) {
            addCriterion("omsCommSysPara.f_sys0_del_user >", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserGreaterThanOrEqualTo(Long value) {
            addCriterion("omsCommSysPara.f_sys0_del_user >=", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserLessThan(Long value) {
            addCriterion("omsCommSysPara.f_sys0_del_user <", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserLessThanOrEqualTo(Long value) {
            addCriterion("omsCommSysPara.f_sys0_del_user <=", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserIn(List<Long> values) {
            addCriterion("omsCommSysPara.f_sys0_del_user in", values, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserNotIn(List<Long> values) {
            addCriterion("omsCommSysPara.f_sys0_del_user not in", values, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserBetween(Long value1, Long value2) {
            addCriterion("omsCommSysPara.f_sys0_del_user between", value1, value2, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserNotBetween(Long value1, Long value2) {
            addCriterion("omsCommSysPara.f_sys0_del_user not between", value1, value2, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateIsNull() {
            addCriterion("omsCommSysPara.f_sys0_del_state is null");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateIsNotNull() {
            addCriterion("omsCommSysPara.f_sys0_del_state is not null");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateEqualTo(Byte value) {
            addCriterion("omsCommSysPara.f_sys0_del_state =", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateNotEqualTo(Byte value) {
            addCriterion("omsCommSysPara.f_sys0_del_state <>", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateGreaterThan(Byte value) {
            addCriterion("omsCommSysPara.f_sys0_del_state >", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("omsCommSysPara.f_sys0_del_state >=", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateLessThan(Byte value) {
            addCriterion("omsCommSysPara.f_sys0_del_state <", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateLessThanOrEqualTo(Byte value) {
            addCriterion("omsCommSysPara.f_sys0_del_state <=", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateIn(List<Byte> values) {
            addCriterion("omsCommSysPara.f_sys0_del_state in", values, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateNotIn(List<Byte> values) {
            addCriterion("omsCommSysPara.f_sys0_del_state not in", values, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateBetween(Byte value1, Byte value2) {
            addCriterion("omsCommSysPara.f_sys0_del_state between", value1, value2, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateNotBetween(Byte value1, Byte value2) {
            addCriterion("omsCommSysPara.f_sys0_del_state not between", value1, value2, "sys0DelState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_oms_comm_sys_para
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_oms_comm_sys_para
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}