package org.prcode.basedomain.business.user.domain;

import java.util.Date;
import org.prcode.basedomain.base.BaseDomain;

public class User extends BaseDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_hua_id
     *
     * @mbg.generated
     */
    private String huaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_real_name
     *
     * @mbg.generated
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_imgProfile
     *
     * @mbg.generated
     */
    private String imgprofile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_default_room_id
     *
     * @mbg.generated
     */
    private Long defaultRoomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_main_room_id
     *
     * @mbg.generated
     */
    private Long mainRoomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_utm_campaign
     *
     * @mbg.generated
     */
    private String utmCampaign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_utm_content
     *
     * @mbg.generated
     */
    private String utmContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_is_first_login_status
     *
     * @mbg.generated
     */
    private Byte isFirstLoginStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_user_state
     *
     * @mbg.generated
     */
    private Integer userState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.t_channel_sub_f_id
     *
     * @mbg.generated
     */
    private Integer channelSubFId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_invite_no
     *
     * @mbg.generated
     */
    private String inviteNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_passwd_status
     *
     * @mbg.generated
     */
    private Byte passwdStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_last_pwderr_time
     *
     * @mbg.generated
     */
    private Date lastPwderrTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_last_login_time
     *
     * @mbg.generated
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_last_pwdmod_time
     *
     * @mbg.generated
     */
    private Date lastPwdmodTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_last_pwd_reset_time
     *
     * @mbg.generated
     */
    private Date lastPwdResetTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_device_id
     *
     * @mbg.generated
     */
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_signature
     *
     * @mbg.generated
     */
    private String signature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_channel
     *
     * @mbg.generated
     */
    private String channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_version
     *
     * @mbg.generated
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_family_role
     *
     * @mbg.generated
     */
    private Byte familyRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_sys0_del_time
     *
     * @mbg.generated
     */
    private Date sys0DelTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_sys0_del_state
     *
     * @mbg.generated
     */
    private Byte sys0DelState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.t_oms_user_f_id
     *
     * @mbg.generated
     */
    private Long omsUserFId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.f_phone_bind_state
     *
     * @mbg.generated
     */
    private Byte phoneBindState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_id
     *
     * @return the value of t_user.f_id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_id
     *
     * @param id the value for t_user.f_id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_mobile
     *
     * @return the value of t_user.f_mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_mobile
     *
     * @param mobile the value for t_user.f_mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_hua_id
     *
     * @return the value of t_user.f_hua_id
     *
     * @mbg.generated
     */
    public String getHuaId() {
        return huaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_hua_id
     *
     * @param huaId the value for t_user.f_hua_id
     *
     * @mbg.generated
     */
    public void setHuaId(String huaId) {
        this.huaId = huaId == null ? null : huaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_nick_name
     *
     * @return the value of t_user.f_nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_nick_name
     *
     * @param nickName the value for t_user.f_nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_real_name
     *
     * @return the value of t_user.f_real_name
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_real_name
     *
     * @param realName the value for t_user.f_real_name
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_sex
     *
     * @return the value of t_user.f_sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_sex
     *
     * @param sex the value for t_user.f_sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_birthday
     *
     * @return the value of t_user.f_birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_birthday
     *
     * @param birthday the value for t_user.f_birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_imgProfile
     *
     * @return the value of t_user.f_imgProfile
     *
     * @mbg.generated
     */
    public String getImgprofile() {
        return imgprofile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_imgProfile
     *
     * @param imgprofile the value for t_user.f_imgProfile
     *
     * @mbg.generated
     */
    public void setImgprofile(String imgprofile) {
        this.imgprofile = imgprofile == null ? null : imgprofile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_default_room_id
     *
     * @return the value of t_user.f_default_room_id
     *
     * @mbg.generated
     */
    public Long getDefaultRoomId() {
        return defaultRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_default_room_id
     *
     * @param defaultRoomId the value for t_user.f_default_room_id
     *
     * @mbg.generated
     */
    public void setDefaultRoomId(Long defaultRoomId) {
        this.defaultRoomId = defaultRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_main_room_id
     *
     * @return the value of t_user.f_main_room_id
     *
     * @mbg.generated
     */
    public Long getMainRoomId() {
        return mainRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_main_room_id
     *
     * @param mainRoomId the value for t_user.f_main_room_id
     *
     * @mbg.generated
     */
    public void setMainRoomId(Long mainRoomId) {
        this.mainRoomId = mainRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_utm_campaign
     *
     * @return the value of t_user.f_utm_campaign
     *
     * @mbg.generated
     */
    public String getUtmCampaign() {
        return utmCampaign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_utm_campaign
     *
     * @param utmCampaign the value for t_user.f_utm_campaign
     *
     * @mbg.generated
     */
    public void setUtmCampaign(String utmCampaign) {
        this.utmCampaign = utmCampaign == null ? null : utmCampaign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_utm_content
     *
     * @return the value of t_user.f_utm_content
     *
     * @mbg.generated
     */
    public String getUtmContent() {
        return utmContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_utm_content
     *
     * @param utmContent the value for t_user.f_utm_content
     *
     * @mbg.generated
     */
    public void setUtmContent(String utmContent) {
        this.utmContent = utmContent == null ? null : utmContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_is_first_login_status
     *
     * @return the value of t_user.f_is_first_login_status
     *
     * @mbg.generated
     */
    public Byte getIsFirstLoginStatus() {
        return isFirstLoginStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_is_first_login_status
     *
     * @param isFirstLoginStatus the value for t_user.f_is_first_login_status
     *
     * @mbg.generated
     */
    public void setIsFirstLoginStatus(Byte isFirstLoginStatus) {
        this.isFirstLoginStatus = isFirstLoginStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_user_state
     *
     * @return the value of t_user.f_user_state
     *
     * @mbg.generated
     */
    public Integer getUserState() {
        return userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_user_state
     *
     * @param userState the value for t_user.f_user_state
     *
     * @mbg.generated
     */
    public void setUserState(Integer userState) {
        this.userState = userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.t_channel_sub_f_id
     *
     * @return the value of t_user.t_channel_sub_f_id
     *
     * @mbg.generated
     */
    public Integer getChannelSubFId() {
        return channelSubFId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.t_channel_sub_f_id
     *
     * @param channelSubFId the value for t_user.t_channel_sub_f_id
     *
     * @mbg.generated
     */
    public void setChannelSubFId(Integer channelSubFId) {
        this.channelSubFId = channelSubFId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_invite_no
     *
     * @return the value of t_user.f_invite_no
     *
     * @mbg.generated
     */
    public String getInviteNo() {
        return inviteNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_invite_no
     *
     * @param inviteNo the value for t_user.f_invite_no
     *
     * @mbg.generated
     */
    public void setInviteNo(String inviteNo) {
        this.inviteNo = inviteNo == null ? null : inviteNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_passwd_status
     *
     * @return the value of t_user.f_passwd_status
     *
     * @mbg.generated
     */
    public Byte getPasswdStatus() {
        return passwdStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_passwd_status
     *
     * @param passwdStatus the value for t_user.f_passwd_status
     *
     * @mbg.generated
     */
    public void setPasswdStatus(Byte passwdStatus) {
        this.passwdStatus = passwdStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_last_pwderr_time
     *
     * @return the value of t_user.f_last_pwderr_time
     *
     * @mbg.generated
     */
    public Date getLastPwderrTime() {
        return lastPwderrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_last_pwderr_time
     *
     * @param lastPwderrTime the value for t_user.f_last_pwderr_time
     *
     * @mbg.generated
     */
    public void setLastPwderrTime(Date lastPwderrTime) {
        this.lastPwderrTime = lastPwderrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_last_login_time
     *
     * @return the value of t_user.f_last_login_time
     *
     * @mbg.generated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_last_login_time
     *
     * @param lastLoginTime the value for t_user.f_last_login_time
     *
     * @mbg.generated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_last_pwdmod_time
     *
     * @return the value of t_user.f_last_pwdmod_time
     *
     * @mbg.generated
     */
    public Date getLastPwdmodTime() {
        return lastPwdmodTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_last_pwdmod_time
     *
     * @param lastPwdmodTime the value for t_user.f_last_pwdmod_time
     *
     * @mbg.generated
     */
    public void setLastPwdmodTime(Date lastPwdmodTime) {
        this.lastPwdmodTime = lastPwdmodTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_last_pwd_reset_time
     *
     * @return the value of t_user.f_last_pwd_reset_time
     *
     * @mbg.generated
     */
    public Date getLastPwdResetTime() {
        return lastPwdResetTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_last_pwd_reset_time
     *
     * @param lastPwdResetTime the value for t_user.f_last_pwd_reset_time
     *
     * @mbg.generated
     */
    public void setLastPwdResetTime(Date lastPwdResetTime) {
        this.lastPwdResetTime = lastPwdResetTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_device_id
     *
     * @return the value of t_user.f_device_id
     *
     * @mbg.generated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_device_id
     *
     * @param deviceId the value for t_user.f_device_id
     *
     * @mbg.generated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_signature
     *
     * @return the value of t_user.f_signature
     *
     * @mbg.generated
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_signature
     *
     * @param signature the value for t_user.f_signature
     *
     * @mbg.generated
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_channel
     *
     * @return the value of t_user.f_channel
     *
     * @mbg.generated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_channel
     *
     * @param channel the value for t_user.f_channel
     *
     * @mbg.generated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_version
     *
     * @return the value of t_user.f_version
     *
     * @mbg.generated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_version
     *
     * @param version the value for t_user.f_version
     *
     * @mbg.generated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_family_role
     *
     * @return the value of t_user.f_family_role
     *
     * @mbg.generated
     */
    public Byte getFamilyRole() {
        return familyRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_family_role
     *
     * @param familyRole the value for t_user.f_family_role
     *
     * @mbg.generated
     */
    public void setFamilyRole(Byte familyRole) {
        this.familyRole = familyRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_sys0_del_time
     *
     * @return the value of t_user.f_sys0_del_time
     *
     * @mbg.generated
     */
    public Date getSys0DelTime() {
        return sys0DelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_sys0_del_time
     *
     * @param sys0DelTime the value for t_user.f_sys0_del_time
     *
     * @mbg.generated
     */
    public void setSys0DelTime(Date sys0DelTime) {
        this.sys0DelTime = sys0DelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_sys0_del_state
     *
     * @return the value of t_user.f_sys0_del_state
     *
     * @mbg.generated
     */
    public Byte getSys0DelState() {
        return sys0DelState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_sys0_del_state
     *
     * @param sys0DelState the value for t_user.f_sys0_del_state
     *
     * @mbg.generated
     */
    public void setSys0DelState(Byte sys0DelState) {
        this.sys0DelState = sys0DelState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.t_oms_user_f_id
     *
     * @return the value of t_user.t_oms_user_f_id
     *
     * @mbg.generated
     */
    public Long getOmsUserFId() {
        return omsUserFId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.t_oms_user_f_id
     *
     * @param omsUserFId the value for t_user.t_oms_user_f_id
     *
     * @mbg.generated
     */
    public void setOmsUserFId(Long omsUserFId) {
        this.omsUserFId = omsUserFId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.f_phone_bind_state
     *
     * @return the value of t_user.f_phone_bind_state
     *
     * @mbg.generated
     */
    public Byte getPhoneBindState() {
        return phoneBindState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.f_phone_bind_state
     *
     * @param phoneBindState the value for t_user.f_phone_bind_state
     *
     * @mbg.generated
     */
    public void setPhoneBindState(Byte phoneBindState) {
        this.phoneBindState = phoneBindState;
    }
}