package org.prcode.basedomain.business.user.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("user.f_id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("user.f_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("user.f_id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("user.f_id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("user.f_id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user.f_id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("user.f_id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("user.f_id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("user.f_id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("user.f_id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("user.f_id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("user.f_id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("user.f_mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("user.f_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("user.f_mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("user.f_mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("user.f_mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("user.f_mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("user.f_mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("user.f_mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("user.f_mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("user.f_mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("user.f_mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("user.f_mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("user.f_mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("user.f_mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andHuaIdIsNull() {
            addCriterion("user.f_hua_id is null");
            return (Criteria) this;
        }

        public Criteria andHuaIdIsNotNull() {
            addCriterion("user.f_hua_id is not null");
            return (Criteria) this;
        }

        public Criteria andHuaIdEqualTo(String value) {
            addCriterion("user.f_hua_id =", value, "huaId");
            return (Criteria) this;
        }

        public Criteria andHuaIdNotEqualTo(String value) {
            addCriterion("user.f_hua_id <>", value, "huaId");
            return (Criteria) this;
        }

        public Criteria andHuaIdGreaterThan(String value) {
            addCriterion("user.f_hua_id >", value, "huaId");
            return (Criteria) this;
        }

        public Criteria andHuaIdGreaterThanOrEqualTo(String value) {
            addCriterion("user.f_hua_id >=", value, "huaId");
            return (Criteria) this;
        }

        public Criteria andHuaIdLessThan(String value) {
            addCriterion("user.f_hua_id <", value, "huaId");
            return (Criteria) this;
        }

        public Criteria andHuaIdLessThanOrEqualTo(String value) {
            addCriterion("user.f_hua_id <=", value, "huaId");
            return (Criteria) this;
        }

        public Criteria andHuaIdLike(String value) {
            addCriterion("user.f_hua_id like", value, "huaId");
            return (Criteria) this;
        }

        public Criteria andHuaIdNotLike(String value) {
            addCriterion("user.f_hua_id not like", value, "huaId");
            return (Criteria) this;
        }

        public Criteria andHuaIdIn(List<String> values) {
            addCriterion("user.f_hua_id in", values, "huaId");
            return (Criteria) this;
        }

        public Criteria andHuaIdNotIn(List<String> values) {
            addCriterion("user.f_hua_id not in", values, "huaId");
            return (Criteria) this;
        }

        public Criteria andHuaIdBetween(String value1, String value2) {
            addCriterion("user.f_hua_id between", value1, value2, "huaId");
            return (Criteria) this;
        }

        public Criteria andHuaIdNotBetween(String value1, String value2) {
            addCriterion("user.f_hua_id not between", value1, value2, "huaId");
            return (Criteria) this;
        }

        public Criteria andNickNameIsNull() {
            addCriterion("user.f_nick_name is null");
            return (Criteria) this;
        }

        public Criteria andNickNameIsNotNull() {
            addCriterion("user.f_nick_name is not null");
            return (Criteria) this;
        }

        public Criteria andNickNameEqualTo(String value) {
            addCriterion("user.f_nick_name =", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotEqualTo(String value) {
            addCriterion("user.f_nick_name <>", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameGreaterThan(String value) {
            addCriterion("user.f_nick_name >", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameGreaterThanOrEqualTo(String value) {
            addCriterion("user.f_nick_name >=", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLessThan(String value) {
            addCriterion("user.f_nick_name <", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLessThanOrEqualTo(String value) {
            addCriterion("user.f_nick_name <=", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLike(String value) {
            addCriterion("user.f_nick_name like", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotLike(String value) {
            addCriterion("user.f_nick_name not like", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameIn(List<String> values) {
            addCriterion("user.f_nick_name in", values, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotIn(List<String> values) {
            addCriterion("user.f_nick_name not in", values, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameBetween(String value1, String value2) {
            addCriterion("user.f_nick_name between", value1, value2, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotBetween(String value1, String value2) {
            addCriterion("user.f_nick_name not between", value1, value2, "nickName");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNull() {
            addCriterion("user.f_real_name is null");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNotNull() {
            addCriterion("user.f_real_name is not null");
            return (Criteria) this;
        }

        public Criteria andRealNameEqualTo(String value) {
            addCriterion("user.f_real_name =", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotEqualTo(String value) {
            addCriterion("user.f_real_name <>", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThan(String value) {
            addCriterion("user.f_real_name >", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThanOrEqualTo(String value) {
            addCriterion("user.f_real_name >=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThan(String value) {
            addCriterion("user.f_real_name <", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThanOrEqualTo(String value) {
            addCriterion("user.f_real_name <=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLike(String value) {
            addCriterion("user.f_real_name like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotLike(String value) {
            addCriterion("user.f_real_name not like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameIn(List<String> values) {
            addCriterion("user.f_real_name in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotIn(List<String> values) {
            addCriterion("user.f_real_name not in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameBetween(String value1, String value2) {
            addCriterion("user.f_real_name between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotBetween(String value1, String value2) {
            addCriterion("user.f_real_name not between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("user.f_sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("user.f_sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("user.f_sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("user.f_sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("user.f_sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("user.f_sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("user.f_sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("user.f_sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("user.f_sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("user.f_sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("user.f_sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("user.f_sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("user.f_sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("user.f_sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("user.f_birthday is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("user.f_birthday is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(Date value) {
            addCriterion("user.f_birthday =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(Date value) {
            addCriterion("user.f_birthday <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(Date value) {
            addCriterion("user.f_birthday >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterion("user.f_birthday >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(Date value) {
            addCriterion("user.f_birthday <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(Date value) {
            addCriterion("user.f_birthday <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<Date> values) {
            addCriterion("user.f_birthday in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<Date> values) {
            addCriterion("user.f_birthday not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(Date value1, Date value2) {
            addCriterion("user.f_birthday between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(Date value1, Date value2) {
            addCriterion("user.f_birthday not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andImgprofileIsNull() {
            addCriterion("user.f_imgProfile is null");
            return (Criteria) this;
        }

        public Criteria andImgprofileIsNotNull() {
            addCriterion("user.f_imgProfile is not null");
            return (Criteria) this;
        }

        public Criteria andImgprofileEqualTo(String value) {
            addCriterion("user.f_imgProfile =", value, "imgprofile");
            return (Criteria) this;
        }

        public Criteria andImgprofileNotEqualTo(String value) {
            addCriterion("user.f_imgProfile <>", value, "imgprofile");
            return (Criteria) this;
        }

        public Criteria andImgprofileGreaterThan(String value) {
            addCriterion("user.f_imgProfile >", value, "imgprofile");
            return (Criteria) this;
        }

        public Criteria andImgprofileGreaterThanOrEqualTo(String value) {
            addCriterion("user.f_imgProfile >=", value, "imgprofile");
            return (Criteria) this;
        }

        public Criteria andImgprofileLessThan(String value) {
            addCriterion("user.f_imgProfile <", value, "imgprofile");
            return (Criteria) this;
        }

        public Criteria andImgprofileLessThanOrEqualTo(String value) {
            addCriterion("user.f_imgProfile <=", value, "imgprofile");
            return (Criteria) this;
        }

        public Criteria andImgprofileLike(String value) {
            addCriterion("user.f_imgProfile like", value, "imgprofile");
            return (Criteria) this;
        }

        public Criteria andImgprofileNotLike(String value) {
            addCriterion("user.f_imgProfile not like", value, "imgprofile");
            return (Criteria) this;
        }

        public Criteria andImgprofileIn(List<String> values) {
            addCriterion("user.f_imgProfile in", values, "imgprofile");
            return (Criteria) this;
        }

        public Criteria andImgprofileNotIn(List<String> values) {
            addCriterion("user.f_imgProfile not in", values, "imgprofile");
            return (Criteria) this;
        }

        public Criteria andImgprofileBetween(String value1, String value2) {
            addCriterion("user.f_imgProfile between", value1, value2, "imgprofile");
            return (Criteria) this;
        }

        public Criteria andImgprofileNotBetween(String value1, String value2) {
            addCriterion("user.f_imgProfile not between", value1, value2, "imgprofile");
            return (Criteria) this;
        }

        public Criteria andDefaultRoomIdIsNull() {
            addCriterion("user.f_default_room_id is null");
            return (Criteria) this;
        }

        public Criteria andDefaultRoomIdIsNotNull() {
            addCriterion("user.f_default_room_id is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultRoomIdEqualTo(Long value) {
            addCriterion("user.f_default_room_id =", value, "defaultRoomId");
            return (Criteria) this;
        }

        public Criteria andDefaultRoomIdNotEqualTo(Long value) {
            addCriterion("user.f_default_room_id <>", value, "defaultRoomId");
            return (Criteria) this;
        }

        public Criteria andDefaultRoomIdGreaterThan(Long value) {
            addCriterion("user.f_default_room_id >", value, "defaultRoomId");
            return (Criteria) this;
        }

        public Criteria andDefaultRoomIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user.f_default_room_id >=", value, "defaultRoomId");
            return (Criteria) this;
        }

        public Criteria andDefaultRoomIdLessThan(Long value) {
            addCriterion("user.f_default_room_id <", value, "defaultRoomId");
            return (Criteria) this;
        }

        public Criteria andDefaultRoomIdLessThanOrEqualTo(Long value) {
            addCriterion("user.f_default_room_id <=", value, "defaultRoomId");
            return (Criteria) this;
        }

        public Criteria andDefaultRoomIdIn(List<Long> values) {
            addCriterion("user.f_default_room_id in", values, "defaultRoomId");
            return (Criteria) this;
        }

        public Criteria andDefaultRoomIdNotIn(List<Long> values) {
            addCriterion("user.f_default_room_id not in", values, "defaultRoomId");
            return (Criteria) this;
        }

        public Criteria andDefaultRoomIdBetween(Long value1, Long value2) {
            addCriterion("user.f_default_room_id between", value1, value2, "defaultRoomId");
            return (Criteria) this;
        }

        public Criteria andDefaultRoomIdNotBetween(Long value1, Long value2) {
            addCriterion("user.f_default_room_id not between", value1, value2, "defaultRoomId");
            return (Criteria) this;
        }

        public Criteria andMainRoomIdIsNull() {
            addCriterion("user.f_main_room_id is null");
            return (Criteria) this;
        }

        public Criteria andMainRoomIdIsNotNull() {
            addCriterion("user.f_main_room_id is not null");
            return (Criteria) this;
        }

        public Criteria andMainRoomIdEqualTo(Long value) {
            addCriterion("user.f_main_room_id =", value, "mainRoomId");
            return (Criteria) this;
        }

        public Criteria andMainRoomIdNotEqualTo(Long value) {
            addCriterion("user.f_main_room_id <>", value, "mainRoomId");
            return (Criteria) this;
        }

        public Criteria andMainRoomIdGreaterThan(Long value) {
            addCriterion("user.f_main_room_id >", value, "mainRoomId");
            return (Criteria) this;
        }

        public Criteria andMainRoomIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user.f_main_room_id >=", value, "mainRoomId");
            return (Criteria) this;
        }

        public Criteria andMainRoomIdLessThan(Long value) {
            addCriterion("user.f_main_room_id <", value, "mainRoomId");
            return (Criteria) this;
        }

        public Criteria andMainRoomIdLessThanOrEqualTo(Long value) {
            addCriterion("user.f_main_room_id <=", value, "mainRoomId");
            return (Criteria) this;
        }

        public Criteria andMainRoomIdIn(List<Long> values) {
            addCriterion("user.f_main_room_id in", values, "mainRoomId");
            return (Criteria) this;
        }

        public Criteria andMainRoomIdNotIn(List<Long> values) {
            addCriterion("user.f_main_room_id not in", values, "mainRoomId");
            return (Criteria) this;
        }

        public Criteria andMainRoomIdBetween(Long value1, Long value2) {
            addCriterion("user.f_main_room_id between", value1, value2, "mainRoomId");
            return (Criteria) this;
        }

        public Criteria andMainRoomIdNotBetween(Long value1, Long value2) {
            addCriterion("user.f_main_room_id not between", value1, value2, "mainRoomId");
            return (Criteria) this;
        }

        public Criteria andUtmCampaignIsNull() {
            addCriterion("user.f_utm_campaign is null");
            return (Criteria) this;
        }

        public Criteria andUtmCampaignIsNotNull() {
            addCriterion("user.f_utm_campaign is not null");
            return (Criteria) this;
        }

        public Criteria andUtmCampaignEqualTo(String value) {
            addCriterion("user.f_utm_campaign =", value, "utmCampaign");
            return (Criteria) this;
        }

        public Criteria andUtmCampaignNotEqualTo(String value) {
            addCriterion("user.f_utm_campaign <>", value, "utmCampaign");
            return (Criteria) this;
        }

        public Criteria andUtmCampaignGreaterThan(String value) {
            addCriterion("user.f_utm_campaign >", value, "utmCampaign");
            return (Criteria) this;
        }

        public Criteria andUtmCampaignGreaterThanOrEqualTo(String value) {
            addCriterion("user.f_utm_campaign >=", value, "utmCampaign");
            return (Criteria) this;
        }

        public Criteria andUtmCampaignLessThan(String value) {
            addCriterion("user.f_utm_campaign <", value, "utmCampaign");
            return (Criteria) this;
        }

        public Criteria andUtmCampaignLessThanOrEqualTo(String value) {
            addCriterion("user.f_utm_campaign <=", value, "utmCampaign");
            return (Criteria) this;
        }

        public Criteria andUtmCampaignLike(String value) {
            addCriterion("user.f_utm_campaign like", value, "utmCampaign");
            return (Criteria) this;
        }

        public Criteria andUtmCampaignNotLike(String value) {
            addCriterion("user.f_utm_campaign not like", value, "utmCampaign");
            return (Criteria) this;
        }

        public Criteria andUtmCampaignIn(List<String> values) {
            addCriterion("user.f_utm_campaign in", values, "utmCampaign");
            return (Criteria) this;
        }

        public Criteria andUtmCampaignNotIn(List<String> values) {
            addCriterion("user.f_utm_campaign not in", values, "utmCampaign");
            return (Criteria) this;
        }

        public Criteria andUtmCampaignBetween(String value1, String value2) {
            addCriterion("user.f_utm_campaign between", value1, value2, "utmCampaign");
            return (Criteria) this;
        }

        public Criteria andUtmCampaignNotBetween(String value1, String value2) {
            addCriterion("user.f_utm_campaign not between", value1, value2, "utmCampaign");
            return (Criteria) this;
        }

        public Criteria andUtmContentIsNull() {
            addCriterion("user.f_utm_content is null");
            return (Criteria) this;
        }

        public Criteria andUtmContentIsNotNull() {
            addCriterion("user.f_utm_content is not null");
            return (Criteria) this;
        }

        public Criteria andUtmContentEqualTo(String value) {
            addCriterion("user.f_utm_content =", value, "utmContent");
            return (Criteria) this;
        }

        public Criteria andUtmContentNotEqualTo(String value) {
            addCriterion("user.f_utm_content <>", value, "utmContent");
            return (Criteria) this;
        }

        public Criteria andUtmContentGreaterThan(String value) {
            addCriterion("user.f_utm_content >", value, "utmContent");
            return (Criteria) this;
        }

        public Criteria andUtmContentGreaterThanOrEqualTo(String value) {
            addCriterion("user.f_utm_content >=", value, "utmContent");
            return (Criteria) this;
        }

        public Criteria andUtmContentLessThan(String value) {
            addCriterion("user.f_utm_content <", value, "utmContent");
            return (Criteria) this;
        }

        public Criteria andUtmContentLessThanOrEqualTo(String value) {
            addCriterion("user.f_utm_content <=", value, "utmContent");
            return (Criteria) this;
        }

        public Criteria andUtmContentLike(String value) {
            addCriterion("user.f_utm_content like", value, "utmContent");
            return (Criteria) this;
        }

        public Criteria andUtmContentNotLike(String value) {
            addCriterion("user.f_utm_content not like", value, "utmContent");
            return (Criteria) this;
        }

        public Criteria andUtmContentIn(List<String> values) {
            addCriterion("user.f_utm_content in", values, "utmContent");
            return (Criteria) this;
        }

        public Criteria andUtmContentNotIn(List<String> values) {
            addCriterion("user.f_utm_content not in", values, "utmContent");
            return (Criteria) this;
        }

        public Criteria andUtmContentBetween(String value1, String value2) {
            addCriterion("user.f_utm_content between", value1, value2, "utmContent");
            return (Criteria) this;
        }

        public Criteria andUtmContentNotBetween(String value1, String value2) {
            addCriterion("user.f_utm_content not between", value1, value2, "utmContent");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginStatusIsNull() {
            addCriterion("user.f_is_first_login_status is null");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginStatusIsNotNull() {
            addCriterion("user.f_is_first_login_status is not null");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginStatusEqualTo(Byte value) {
            addCriterion("user.f_is_first_login_status =", value, "isFirstLoginStatus");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginStatusNotEqualTo(Byte value) {
            addCriterion("user.f_is_first_login_status <>", value, "isFirstLoginStatus");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginStatusGreaterThan(Byte value) {
            addCriterion("user.f_is_first_login_status >", value, "isFirstLoginStatus");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("user.f_is_first_login_status >=", value, "isFirstLoginStatus");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginStatusLessThan(Byte value) {
            addCriterion("user.f_is_first_login_status <", value, "isFirstLoginStatus");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginStatusLessThanOrEqualTo(Byte value) {
            addCriterion("user.f_is_first_login_status <=", value, "isFirstLoginStatus");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginStatusIn(List<Byte> values) {
            addCriterion("user.f_is_first_login_status in", values, "isFirstLoginStatus");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginStatusNotIn(List<Byte> values) {
            addCriterion("user.f_is_first_login_status not in", values, "isFirstLoginStatus");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginStatusBetween(Byte value1, Byte value2) {
            addCriterion("user.f_is_first_login_status between", value1, value2, "isFirstLoginStatus");
            return (Criteria) this;
        }

        public Criteria andIsFirstLoginStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("user.f_is_first_login_status not between", value1, value2, "isFirstLoginStatus");
            return (Criteria) this;
        }

        public Criteria andUserStateIsNull() {
            addCriterion("user.f_user_state is null");
            return (Criteria) this;
        }

        public Criteria andUserStateIsNotNull() {
            addCriterion("user.f_user_state is not null");
            return (Criteria) this;
        }

        public Criteria andUserStateEqualTo(Integer value) {
            addCriterion("user.f_user_state =", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateNotEqualTo(Integer value) {
            addCriterion("user.f_user_state <>", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateGreaterThan(Integer value) {
            addCriterion("user.f_user_state >", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("user.f_user_state >=", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateLessThan(Integer value) {
            addCriterion("user.f_user_state <", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateLessThanOrEqualTo(Integer value) {
            addCriterion("user.f_user_state <=", value, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateIn(List<Integer> values) {
            addCriterion("user.f_user_state in", values, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateNotIn(List<Integer> values) {
            addCriterion("user.f_user_state not in", values, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateBetween(Integer value1, Integer value2) {
            addCriterion("user.f_user_state between", value1, value2, "userState");
            return (Criteria) this;
        }

        public Criteria andUserStateNotBetween(Integer value1, Integer value2) {
            addCriterion("user.f_user_state not between", value1, value2, "userState");
            return (Criteria) this;
        }

        public Criteria andChannelSubFIdIsNull() {
            addCriterion("user.t_channel_sub_f_id is null");
            return (Criteria) this;
        }

        public Criteria andChannelSubFIdIsNotNull() {
            addCriterion("user.t_channel_sub_f_id is not null");
            return (Criteria) this;
        }

        public Criteria andChannelSubFIdEqualTo(Integer value) {
            addCriterion("user.t_channel_sub_f_id =", value, "channelSubFId");
            return (Criteria) this;
        }

        public Criteria andChannelSubFIdNotEqualTo(Integer value) {
            addCriterion("user.t_channel_sub_f_id <>", value, "channelSubFId");
            return (Criteria) this;
        }

        public Criteria andChannelSubFIdGreaterThan(Integer value) {
            addCriterion("user.t_channel_sub_f_id >", value, "channelSubFId");
            return (Criteria) this;
        }

        public Criteria andChannelSubFIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user.t_channel_sub_f_id >=", value, "channelSubFId");
            return (Criteria) this;
        }

        public Criteria andChannelSubFIdLessThan(Integer value) {
            addCriterion("user.t_channel_sub_f_id <", value, "channelSubFId");
            return (Criteria) this;
        }

        public Criteria andChannelSubFIdLessThanOrEqualTo(Integer value) {
            addCriterion("user.t_channel_sub_f_id <=", value, "channelSubFId");
            return (Criteria) this;
        }

        public Criteria andChannelSubFIdIn(List<Integer> values) {
            addCriterion("user.t_channel_sub_f_id in", values, "channelSubFId");
            return (Criteria) this;
        }

        public Criteria andChannelSubFIdNotIn(List<Integer> values) {
            addCriterion("user.t_channel_sub_f_id not in", values, "channelSubFId");
            return (Criteria) this;
        }

        public Criteria andChannelSubFIdBetween(Integer value1, Integer value2) {
            addCriterion("user.t_channel_sub_f_id between", value1, value2, "channelSubFId");
            return (Criteria) this;
        }

        public Criteria andChannelSubFIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user.t_channel_sub_f_id not between", value1, value2, "channelSubFId");
            return (Criteria) this;
        }

        public Criteria andInviteNoIsNull() {
            addCriterion("user.f_invite_no is null");
            return (Criteria) this;
        }

        public Criteria andInviteNoIsNotNull() {
            addCriterion("user.f_invite_no is not null");
            return (Criteria) this;
        }

        public Criteria andInviteNoEqualTo(String value) {
            addCriterion("user.f_invite_no =", value, "inviteNo");
            return (Criteria) this;
        }

        public Criteria andInviteNoNotEqualTo(String value) {
            addCriterion("user.f_invite_no <>", value, "inviteNo");
            return (Criteria) this;
        }

        public Criteria andInviteNoGreaterThan(String value) {
            addCriterion("user.f_invite_no >", value, "inviteNo");
            return (Criteria) this;
        }

        public Criteria andInviteNoGreaterThanOrEqualTo(String value) {
            addCriterion("user.f_invite_no >=", value, "inviteNo");
            return (Criteria) this;
        }

        public Criteria andInviteNoLessThan(String value) {
            addCriterion("user.f_invite_no <", value, "inviteNo");
            return (Criteria) this;
        }

        public Criteria andInviteNoLessThanOrEqualTo(String value) {
            addCriterion("user.f_invite_no <=", value, "inviteNo");
            return (Criteria) this;
        }

        public Criteria andInviteNoLike(String value) {
            addCriterion("user.f_invite_no like", value, "inviteNo");
            return (Criteria) this;
        }

        public Criteria andInviteNoNotLike(String value) {
            addCriterion("user.f_invite_no not like", value, "inviteNo");
            return (Criteria) this;
        }

        public Criteria andInviteNoIn(List<String> values) {
            addCriterion("user.f_invite_no in", values, "inviteNo");
            return (Criteria) this;
        }

        public Criteria andInviteNoNotIn(List<String> values) {
            addCriterion("user.f_invite_no not in", values, "inviteNo");
            return (Criteria) this;
        }

        public Criteria andInviteNoBetween(String value1, String value2) {
            addCriterion("user.f_invite_no between", value1, value2, "inviteNo");
            return (Criteria) this;
        }

        public Criteria andInviteNoNotBetween(String value1, String value2) {
            addCriterion("user.f_invite_no not between", value1, value2, "inviteNo");
            return (Criteria) this;
        }

        public Criteria andPasswdStatusIsNull() {
            addCriterion("user.f_passwd_status is null");
            return (Criteria) this;
        }

        public Criteria andPasswdStatusIsNotNull() {
            addCriterion("user.f_passwd_status is not null");
            return (Criteria) this;
        }

        public Criteria andPasswdStatusEqualTo(Byte value) {
            addCriterion("user.f_passwd_status =", value, "passwdStatus");
            return (Criteria) this;
        }

        public Criteria andPasswdStatusNotEqualTo(Byte value) {
            addCriterion("user.f_passwd_status <>", value, "passwdStatus");
            return (Criteria) this;
        }

        public Criteria andPasswdStatusGreaterThan(Byte value) {
            addCriterion("user.f_passwd_status >", value, "passwdStatus");
            return (Criteria) this;
        }

        public Criteria andPasswdStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("user.f_passwd_status >=", value, "passwdStatus");
            return (Criteria) this;
        }

        public Criteria andPasswdStatusLessThan(Byte value) {
            addCriterion("user.f_passwd_status <", value, "passwdStatus");
            return (Criteria) this;
        }

        public Criteria andPasswdStatusLessThanOrEqualTo(Byte value) {
            addCriterion("user.f_passwd_status <=", value, "passwdStatus");
            return (Criteria) this;
        }

        public Criteria andPasswdStatusIn(List<Byte> values) {
            addCriterion("user.f_passwd_status in", values, "passwdStatus");
            return (Criteria) this;
        }

        public Criteria andPasswdStatusNotIn(List<Byte> values) {
            addCriterion("user.f_passwd_status not in", values, "passwdStatus");
            return (Criteria) this;
        }

        public Criteria andPasswdStatusBetween(Byte value1, Byte value2) {
            addCriterion("user.f_passwd_status between", value1, value2, "passwdStatus");
            return (Criteria) this;
        }

        public Criteria andPasswdStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("user.f_passwd_status not between", value1, value2, "passwdStatus");
            return (Criteria) this;
        }

        public Criteria andLastPwderrTimeIsNull() {
            addCriterion("user.f_last_pwderr_time is null");
            return (Criteria) this;
        }

        public Criteria andLastPwderrTimeIsNotNull() {
            addCriterion("user.f_last_pwderr_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastPwderrTimeEqualTo(Date value) {
            addCriterion("user.f_last_pwderr_time =", value, "lastPwderrTime");
            return (Criteria) this;
        }

        public Criteria andLastPwderrTimeNotEqualTo(Date value) {
            addCriterion("user.f_last_pwderr_time <>", value, "lastPwderrTime");
            return (Criteria) this;
        }

        public Criteria andLastPwderrTimeGreaterThan(Date value) {
            addCriterion("user.f_last_pwderr_time >", value, "lastPwderrTime");
            return (Criteria) this;
        }

        public Criteria andLastPwderrTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("user.f_last_pwderr_time >=", value, "lastPwderrTime");
            return (Criteria) this;
        }

        public Criteria andLastPwderrTimeLessThan(Date value) {
            addCriterion("user.f_last_pwderr_time <", value, "lastPwderrTime");
            return (Criteria) this;
        }

        public Criteria andLastPwderrTimeLessThanOrEqualTo(Date value) {
            addCriterion("user.f_last_pwderr_time <=", value, "lastPwderrTime");
            return (Criteria) this;
        }

        public Criteria andLastPwderrTimeIn(List<Date> values) {
            addCriterion("user.f_last_pwderr_time in", values, "lastPwderrTime");
            return (Criteria) this;
        }

        public Criteria andLastPwderrTimeNotIn(List<Date> values) {
            addCriterion("user.f_last_pwderr_time not in", values, "lastPwderrTime");
            return (Criteria) this;
        }

        public Criteria andLastPwderrTimeBetween(Date value1, Date value2) {
            addCriterion("user.f_last_pwderr_time between", value1, value2, "lastPwderrTime");
            return (Criteria) this;
        }

        public Criteria andLastPwderrTimeNotBetween(Date value1, Date value2) {
            addCriterion("user.f_last_pwderr_time not between", value1, value2, "lastPwderrTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIsNull() {
            addCriterion("user.f_last_login_time is null");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIsNotNull() {
            addCriterion("user.f_last_login_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeEqualTo(Date value) {
            addCriterion("user.f_last_login_time =", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotEqualTo(Date value) {
            addCriterion("user.f_last_login_time <>", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeGreaterThan(Date value) {
            addCriterion("user.f_last_login_time >", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("user.f_last_login_time >=", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeLessThan(Date value) {
            addCriterion("user.f_last_login_time <", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeLessThanOrEqualTo(Date value) {
            addCriterion("user.f_last_login_time <=", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIn(List<Date> values) {
            addCriterion("user.f_last_login_time in", values, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotIn(List<Date> values) {
            addCriterion("user.f_last_login_time not in", values, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeBetween(Date value1, Date value2) {
            addCriterion("user.f_last_login_time between", value1, value2, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotBetween(Date value1, Date value2) {
            addCriterion("user.f_last_login_time not between", value1, value2, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdmodTimeIsNull() {
            addCriterion("user.f_last_pwdmod_time is null");
            return (Criteria) this;
        }

        public Criteria andLastPwdmodTimeIsNotNull() {
            addCriterion("user.f_last_pwdmod_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastPwdmodTimeEqualTo(Date value) {
            addCriterion("user.f_last_pwdmod_time =", value, "lastPwdmodTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdmodTimeNotEqualTo(Date value) {
            addCriterion("user.f_last_pwdmod_time <>", value, "lastPwdmodTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdmodTimeGreaterThan(Date value) {
            addCriterion("user.f_last_pwdmod_time >", value, "lastPwdmodTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdmodTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("user.f_last_pwdmod_time >=", value, "lastPwdmodTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdmodTimeLessThan(Date value) {
            addCriterion("user.f_last_pwdmod_time <", value, "lastPwdmodTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdmodTimeLessThanOrEqualTo(Date value) {
            addCriterion("user.f_last_pwdmod_time <=", value, "lastPwdmodTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdmodTimeIn(List<Date> values) {
            addCriterion("user.f_last_pwdmod_time in", values, "lastPwdmodTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdmodTimeNotIn(List<Date> values) {
            addCriterion("user.f_last_pwdmod_time not in", values, "lastPwdmodTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdmodTimeBetween(Date value1, Date value2) {
            addCriterion("user.f_last_pwdmod_time between", value1, value2, "lastPwdmodTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdmodTimeNotBetween(Date value1, Date value2) {
            addCriterion("user.f_last_pwdmod_time not between", value1, value2, "lastPwdmodTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdResetTimeIsNull() {
            addCriterion("user.f_last_pwd_reset_time is null");
            return (Criteria) this;
        }

        public Criteria andLastPwdResetTimeIsNotNull() {
            addCriterion("user.f_last_pwd_reset_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastPwdResetTimeEqualTo(Date value) {
            addCriterion("user.f_last_pwd_reset_time =", value, "lastPwdResetTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdResetTimeNotEqualTo(Date value) {
            addCriterion("user.f_last_pwd_reset_time <>", value, "lastPwdResetTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdResetTimeGreaterThan(Date value) {
            addCriterion("user.f_last_pwd_reset_time >", value, "lastPwdResetTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdResetTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("user.f_last_pwd_reset_time >=", value, "lastPwdResetTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdResetTimeLessThan(Date value) {
            addCriterion("user.f_last_pwd_reset_time <", value, "lastPwdResetTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdResetTimeLessThanOrEqualTo(Date value) {
            addCriterion("user.f_last_pwd_reset_time <=", value, "lastPwdResetTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdResetTimeIn(List<Date> values) {
            addCriterion("user.f_last_pwd_reset_time in", values, "lastPwdResetTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdResetTimeNotIn(List<Date> values) {
            addCriterion("user.f_last_pwd_reset_time not in", values, "lastPwdResetTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdResetTimeBetween(Date value1, Date value2) {
            addCriterion("user.f_last_pwd_reset_time between", value1, value2, "lastPwdResetTime");
            return (Criteria) this;
        }

        public Criteria andLastPwdResetTimeNotBetween(Date value1, Date value2) {
            addCriterion("user.f_last_pwd_reset_time not between", value1, value2, "lastPwdResetTime");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNull() {
            addCriterion("user.f_device_id is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNotNull() {
            addCriterion("user.f_device_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdEqualTo(String value) {
            addCriterion("user.f_device_id =", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotEqualTo(String value) {
            addCriterion("user.f_device_id <>", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThan(String value) {
            addCriterion("user.f_device_id >", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThanOrEqualTo(String value) {
            addCriterion("user.f_device_id >=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThan(String value) {
            addCriterion("user.f_device_id <", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThanOrEqualTo(String value) {
            addCriterion("user.f_device_id <=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLike(String value) {
            addCriterion("user.f_device_id like", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotLike(String value) {
            addCriterion("user.f_device_id not like", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIn(List<String> values) {
            addCriterion("user.f_device_id in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotIn(List<String> values) {
            addCriterion("user.f_device_id not in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdBetween(String value1, String value2) {
            addCriterion("user.f_device_id between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotBetween(String value1, String value2) {
            addCriterion("user.f_device_id not between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andSignatureIsNull() {
            addCriterion("user.f_signature is null");
            return (Criteria) this;
        }

        public Criteria andSignatureIsNotNull() {
            addCriterion("user.f_signature is not null");
            return (Criteria) this;
        }

        public Criteria andSignatureEqualTo(String value) {
            addCriterion("user.f_signature =", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotEqualTo(String value) {
            addCriterion("user.f_signature <>", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureGreaterThan(String value) {
            addCriterion("user.f_signature >", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureGreaterThanOrEqualTo(String value) {
            addCriterion("user.f_signature >=", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureLessThan(String value) {
            addCriterion("user.f_signature <", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureLessThanOrEqualTo(String value) {
            addCriterion("user.f_signature <=", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureLike(String value) {
            addCriterion("user.f_signature like", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotLike(String value) {
            addCriterion("user.f_signature not like", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureIn(List<String> values) {
            addCriterion("user.f_signature in", values, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotIn(List<String> values) {
            addCriterion("user.f_signature not in", values, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureBetween(String value1, String value2) {
            addCriterion("user.f_signature between", value1, value2, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotBetween(String value1, String value2) {
            addCriterion("user.f_signature not between", value1, value2, "signature");
            return (Criteria) this;
        }

        public Criteria andChannelIsNull() {
            addCriterion("user.f_channel is null");
            return (Criteria) this;
        }

        public Criteria andChannelIsNotNull() {
            addCriterion("user.f_channel is not null");
            return (Criteria) this;
        }

        public Criteria andChannelEqualTo(String value) {
            addCriterion("user.f_channel =", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotEqualTo(String value) {
            addCriterion("user.f_channel <>", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThan(String value) {
            addCriterion("user.f_channel >", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThanOrEqualTo(String value) {
            addCriterion("user.f_channel >=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThan(String value) {
            addCriterion("user.f_channel <", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThanOrEqualTo(String value) {
            addCriterion("user.f_channel <=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLike(String value) {
            addCriterion("user.f_channel like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotLike(String value) {
            addCriterion("user.f_channel not like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelIn(List<String> values) {
            addCriterion("user.f_channel in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotIn(List<String> values) {
            addCriterion("user.f_channel not in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelBetween(String value1, String value2) {
            addCriterion("user.f_channel between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotBetween(String value1, String value2) {
            addCriterion("user.f_channel not between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("user.f_version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("user.f_version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("user.f_version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("user.f_version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("user.f_version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("user.f_version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("user.f_version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("user.f_version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("user.f_version like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("user.f_version not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("user.f_version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("user.f_version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("user.f_version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("user.f_version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andFamilyRoleIsNull() {
            addCriterion("user.f_family_role is null");
            return (Criteria) this;
        }

        public Criteria andFamilyRoleIsNotNull() {
            addCriterion("user.f_family_role is not null");
            return (Criteria) this;
        }

        public Criteria andFamilyRoleEqualTo(Byte value) {
            addCriterion("user.f_family_role =", value, "familyRole");
            return (Criteria) this;
        }

        public Criteria andFamilyRoleNotEqualTo(Byte value) {
            addCriterion("user.f_family_role <>", value, "familyRole");
            return (Criteria) this;
        }

        public Criteria andFamilyRoleGreaterThan(Byte value) {
            addCriterion("user.f_family_role >", value, "familyRole");
            return (Criteria) this;
        }

        public Criteria andFamilyRoleGreaterThanOrEqualTo(Byte value) {
            addCriterion("user.f_family_role >=", value, "familyRole");
            return (Criteria) this;
        }

        public Criteria andFamilyRoleLessThan(Byte value) {
            addCriterion("user.f_family_role <", value, "familyRole");
            return (Criteria) this;
        }

        public Criteria andFamilyRoleLessThanOrEqualTo(Byte value) {
            addCriterion("user.f_family_role <=", value, "familyRole");
            return (Criteria) this;
        }

        public Criteria andFamilyRoleIn(List<Byte> values) {
            addCriterion("user.f_family_role in", values, "familyRole");
            return (Criteria) this;
        }

        public Criteria andFamilyRoleNotIn(List<Byte> values) {
            addCriterion("user.f_family_role not in", values, "familyRole");
            return (Criteria) this;
        }

        public Criteria andFamilyRoleBetween(Byte value1, Byte value2) {
            addCriterion("user.f_family_role between", value1, value2, "familyRole");
            return (Criteria) this;
        }

        public Criteria andFamilyRoleNotBetween(Byte value1, Byte value2) {
            addCriterion("user.f_family_role not between", value1, value2, "familyRole");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeIsNull() {
            addCriterion("user.f_sys0_add_time is null");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeIsNotNull() {
            addCriterion("user.f_sys0_add_time is not null");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeEqualTo(Date value) {
            addCriterion("user.f_sys0_add_time =", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeNotEqualTo(Date value) {
            addCriterion("user.f_sys0_add_time <>", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeGreaterThan(Date value) {
            addCriterion("user.f_sys0_add_time >", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("user.f_sys0_add_time >=", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeLessThan(Date value) {
            addCriterion("user.f_sys0_add_time <", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeLessThanOrEqualTo(Date value) {
            addCriterion("user.f_sys0_add_time <=", value, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeIn(List<Date> values) {
            addCriterion("user.f_sys0_add_time in", values, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeNotIn(List<Date> values) {
            addCriterion("user.f_sys0_add_time not in", values, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeBetween(Date value1, Date value2) {
            addCriterion("user.f_sys0_add_time between", value1, value2, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddTimeNotBetween(Date value1, Date value2) {
            addCriterion("user.f_sys0_add_time not between", value1, value2, "sys0AddTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeIsNull() {
            addCriterion("user.f_sys0_upd_time is null");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeIsNotNull() {
            addCriterion("user.f_sys0_upd_time is not null");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeEqualTo(Date value) {
            addCriterion("user.f_sys0_upd_time =", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeNotEqualTo(Date value) {
            addCriterion("user.f_sys0_upd_time <>", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeGreaterThan(Date value) {
            addCriterion("user.f_sys0_upd_time >", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("user.f_sys0_upd_time >=", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeLessThan(Date value) {
            addCriterion("user.f_sys0_upd_time <", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeLessThanOrEqualTo(Date value) {
            addCriterion("user.f_sys0_upd_time <=", value, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeIn(List<Date> values) {
            addCriterion("user.f_sys0_upd_time in", values, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeNotIn(List<Date> values) {
            addCriterion("user.f_sys0_upd_time not in", values, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeBetween(Date value1, Date value2) {
            addCriterion("user.f_sys0_upd_time between", value1, value2, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0UpdTimeNotBetween(Date value1, Date value2) {
            addCriterion("user.f_sys0_upd_time not between", value1, value2, "sys0UpdTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeIsNull() {
            addCriterion("user.f_sys0_del_time is null");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeIsNotNull() {
            addCriterion("user.f_sys0_del_time is not null");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeEqualTo(Date value) {
            addCriterion("user.f_sys0_del_time =", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeNotEqualTo(Date value) {
            addCriterion("user.f_sys0_del_time <>", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeGreaterThan(Date value) {
            addCriterion("user.f_sys0_del_time >", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("user.f_sys0_del_time >=", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeLessThan(Date value) {
            addCriterion("user.f_sys0_del_time <", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeLessThanOrEqualTo(Date value) {
            addCriterion("user.f_sys0_del_time <=", value, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeIn(List<Date> values) {
            addCriterion("user.f_sys0_del_time in", values, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeNotIn(List<Date> values) {
            addCriterion("user.f_sys0_del_time not in", values, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeBetween(Date value1, Date value2) {
            addCriterion("user.f_sys0_del_time between", value1, value2, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0DelTimeNotBetween(Date value1, Date value2) {
            addCriterion("user.f_sys0_del_time not between", value1, value2, "sys0DelTime");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserIsNull() {
            addCriterion("user.f_sys0_add_user is null");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserIsNotNull() {
            addCriterion("user.f_sys0_add_user is not null");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserEqualTo(Long value) {
            addCriterion("user.f_sys0_add_user =", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserNotEqualTo(Long value) {
            addCriterion("user.f_sys0_add_user <>", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserGreaterThan(Long value) {
            addCriterion("user.f_sys0_add_user >", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserGreaterThanOrEqualTo(Long value) {
            addCriterion("user.f_sys0_add_user >=", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserLessThan(Long value) {
            addCriterion("user.f_sys0_add_user <", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserLessThanOrEqualTo(Long value) {
            addCriterion("user.f_sys0_add_user <=", value, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserIn(List<Long> values) {
            addCriterion("user.f_sys0_add_user in", values, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserNotIn(List<Long> values) {
            addCriterion("user.f_sys0_add_user not in", values, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserBetween(Long value1, Long value2) {
            addCriterion("user.f_sys0_add_user between", value1, value2, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0AddUserNotBetween(Long value1, Long value2) {
            addCriterion("user.f_sys0_add_user not between", value1, value2, "sys0AddUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserIsNull() {
            addCriterion("user.f_sys0_upd_user is null");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserIsNotNull() {
            addCriterion("user.f_sys0_upd_user is not null");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserEqualTo(Long value) {
            addCriterion("user.f_sys0_upd_user =", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserNotEqualTo(Long value) {
            addCriterion("user.f_sys0_upd_user <>", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserGreaterThan(Long value) {
            addCriterion("user.f_sys0_upd_user >", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserGreaterThanOrEqualTo(Long value) {
            addCriterion("user.f_sys0_upd_user >=", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserLessThan(Long value) {
            addCriterion("user.f_sys0_upd_user <", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserLessThanOrEqualTo(Long value) {
            addCriterion("user.f_sys0_upd_user <=", value, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserIn(List<Long> values) {
            addCriterion("user.f_sys0_upd_user in", values, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserNotIn(List<Long> values) {
            addCriterion("user.f_sys0_upd_user not in", values, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserBetween(Long value1, Long value2) {
            addCriterion("user.f_sys0_upd_user between", value1, value2, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0UpdUserNotBetween(Long value1, Long value2) {
            addCriterion("user.f_sys0_upd_user not between", value1, value2, "sys0UpdUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserIsNull() {
            addCriterion("user.f_sys0_del_user is null");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserIsNotNull() {
            addCriterion("user.f_sys0_del_user is not null");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserEqualTo(Long value) {
            addCriterion("user.f_sys0_del_user =", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserNotEqualTo(Long value) {
            addCriterion("user.f_sys0_del_user <>", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserGreaterThan(Long value) {
            addCriterion("user.f_sys0_del_user >", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserGreaterThanOrEqualTo(Long value) {
            addCriterion("user.f_sys0_del_user >=", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserLessThan(Long value) {
            addCriterion("user.f_sys0_del_user <", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserLessThanOrEqualTo(Long value) {
            addCriterion("user.f_sys0_del_user <=", value, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserIn(List<Long> values) {
            addCriterion("user.f_sys0_del_user in", values, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserNotIn(List<Long> values) {
            addCriterion("user.f_sys0_del_user not in", values, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserBetween(Long value1, Long value2) {
            addCriterion("user.f_sys0_del_user between", value1, value2, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelUserNotBetween(Long value1, Long value2) {
            addCriterion("user.f_sys0_del_user not between", value1, value2, "sys0DelUser");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateIsNull() {
            addCriterion("user.f_sys0_del_state is null");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateIsNotNull() {
            addCriterion("user.f_sys0_del_state is not null");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateEqualTo(Byte value) {
            addCriterion("user.f_sys0_del_state =", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateNotEqualTo(Byte value) {
            addCriterion("user.f_sys0_del_state <>", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateGreaterThan(Byte value) {
            addCriterion("user.f_sys0_del_state >", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("user.f_sys0_del_state >=", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateLessThan(Byte value) {
            addCriterion("user.f_sys0_del_state <", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateLessThanOrEqualTo(Byte value) {
            addCriterion("user.f_sys0_del_state <=", value, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateIn(List<Byte> values) {
            addCriterion("user.f_sys0_del_state in", values, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateNotIn(List<Byte> values) {
            addCriterion("user.f_sys0_del_state not in", values, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateBetween(Byte value1, Byte value2) {
            addCriterion("user.f_sys0_del_state between", value1, value2, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andSys0DelStateNotBetween(Byte value1, Byte value2) {
            addCriterion("user.f_sys0_del_state not between", value1, value2, "sys0DelState");
            return (Criteria) this;
        }

        public Criteria andOmsUserFIdIsNull() {
            addCriterion("user.t_oms_user_f_id is null");
            return (Criteria) this;
        }

        public Criteria andOmsUserFIdIsNotNull() {
            addCriterion("user.t_oms_user_f_id is not null");
            return (Criteria) this;
        }

        public Criteria andOmsUserFIdEqualTo(Long value) {
            addCriterion("user.t_oms_user_f_id =", value, "omsUserFId");
            return (Criteria) this;
        }

        public Criteria andOmsUserFIdNotEqualTo(Long value) {
            addCriterion("user.t_oms_user_f_id <>", value, "omsUserFId");
            return (Criteria) this;
        }

        public Criteria andOmsUserFIdGreaterThan(Long value) {
            addCriterion("user.t_oms_user_f_id >", value, "omsUserFId");
            return (Criteria) this;
        }

        public Criteria andOmsUserFIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user.t_oms_user_f_id >=", value, "omsUserFId");
            return (Criteria) this;
        }

        public Criteria andOmsUserFIdLessThan(Long value) {
            addCriterion("user.t_oms_user_f_id <", value, "omsUserFId");
            return (Criteria) this;
        }

        public Criteria andOmsUserFIdLessThanOrEqualTo(Long value) {
            addCriterion("user.t_oms_user_f_id <=", value, "omsUserFId");
            return (Criteria) this;
        }

        public Criteria andOmsUserFIdIn(List<Long> values) {
            addCriterion("user.t_oms_user_f_id in", values, "omsUserFId");
            return (Criteria) this;
        }

        public Criteria andOmsUserFIdNotIn(List<Long> values) {
            addCriterion("user.t_oms_user_f_id not in", values, "omsUserFId");
            return (Criteria) this;
        }

        public Criteria andOmsUserFIdBetween(Long value1, Long value2) {
            addCriterion("user.t_oms_user_f_id between", value1, value2, "omsUserFId");
            return (Criteria) this;
        }

        public Criteria andOmsUserFIdNotBetween(Long value1, Long value2) {
            addCriterion("user.t_oms_user_f_id not between", value1, value2, "omsUserFId");
            return (Criteria) this;
        }

        public Criteria andPhoneBindStateIsNull() {
            addCriterion("user.f_phone_bind_state is null");
            return (Criteria) this;
        }

        public Criteria andPhoneBindStateIsNotNull() {
            addCriterion("user.f_phone_bind_state is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneBindStateEqualTo(Byte value) {
            addCriterion("user.f_phone_bind_state =", value, "phoneBindState");
            return (Criteria) this;
        }

        public Criteria andPhoneBindStateNotEqualTo(Byte value) {
            addCriterion("user.f_phone_bind_state <>", value, "phoneBindState");
            return (Criteria) this;
        }

        public Criteria andPhoneBindStateGreaterThan(Byte value) {
            addCriterion("user.f_phone_bind_state >", value, "phoneBindState");
            return (Criteria) this;
        }

        public Criteria andPhoneBindStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("user.f_phone_bind_state >=", value, "phoneBindState");
            return (Criteria) this;
        }

        public Criteria andPhoneBindStateLessThan(Byte value) {
            addCriterion("user.f_phone_bind_state <", value, "phoneBindState");
            return (Criteria) this;
        }

        public Criteria andPhoneBindStateLessThanOrEqualTo(Byte value) {
            addCriterion("user.f_phone_bind_state <=", value, "phoneBindState");
            return (Criteria) this;
        }

        public Criteria andPhoneBindStateIn(List<Byte> values) {
            addCriterion("user.f_phone_bind_state in", values, "phoneBindState");
            return (Criteria) this;
        }

        public Criteria andPhoneBindStateNotIn(List<Byte> values) {
            addCriterion("user.f_phone_bind_state not in", values, "phoneBindState");
            return (Criteria) this;
        }

        public Criteria andPhoneBindStateBetween(Byte value1, Byte value2) {
            addCriterion("user.f_phone_bind_state between", value1, value2, "phoneBindState");
            return (Criteria) this;
        }

        public Criteria andPhoneBindStateNotBetween(Byte value1, Byte value2) {
            addCriterion("user.f_phone_bind_state not between", value1, value2, "phoneBindState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}