package org.prcode.log.basedomain.commLogger.dao;

import org.prcode.log.basedomain.commLogger.domain.CommLogger;
import org.springframework.stereotype.Repository;

@Repository
public interface CommLoggerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comm_logger
     *
     * @mbg.generated
     */
    int insert(CommLogger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comm_logger
     *
     * @mbg.generated
     */
    int insertSelective(CommLogger record);
}