package org.prcode.basedomain.dredgeType.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.prcode.basedomain.dredgeType.domain.DredgeType;
import org.prcode.basedomain.dredgeType.domain.DredgeTypeExample;
import org.springframework.stereotype.Repository;

@Repository
public interface DredgeTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dredge_type
     *
     * @mbg.generated
     */
    long countByExample(DredgeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dredge_type
     *
     * @mbg.generated
     */
    int insert(DredgeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dredge_type
     *
     * @mbg.generated
     */
    int insertSelective(DredgeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dredge_type
     *
     * @mbg.generated
     */
    List<DredgeType> selectByExample(DredgeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dredge_type
     *
     * @mbg.generated
     */
    DredgeType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dredge_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DredgeType record, @Param("example") DredgeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dredge_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DredgeType record, @Param("example") DredgeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dredge_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DredgeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dredge_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DredgeType record);
}