package org.prcode.basedomain.dredgeType.domain;

import org.prcode.basedomain.base.BaseDomain;

public class DredgeType extends BaseDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dredge_type.f_id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dredge_type.f_code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dredge_type.t_community_supply_type_f_id
     *
     * @mbg.generated
     */
    private Long communitySupplyTypeFId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dredge_type.f_name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dredge_type.f_pic_url
     *
     * @mbg.generated
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dredge_type.f_desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dredge_type.f_price_desc
     *
     * @mbg.generated
     */
    private String priceDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dredge_type.f_id
     *
     * @return the value of t_dredge_type.f_id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dredge_type.f_id
     *
     * @param id the value for t_dredge_type.f_id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dredge_type.f_code
     *
     * @return the value of t_dredge_type.f_code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dredge_type.f_code
     *
     * @param code the value for t_dredge_type.f_code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dredge_type.t_community_supply_type_f_id
     *
     * @return the value of t_dredge_type.t_community_supply_type_f_id
     *
     * @mbg.generated
     */
    public Long getCommunitySupplyTypeFId() {
        return communitySupplyTypeFId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dredge_type.t_community_supply_type_f_id
     *
     * @param communitySupplyTypeFId the value for t_dredge_type.t_community_supply_type_f_id
     *
     * @mbg.generated
     */
    public void setCommunitySupplyTypeFId(Long communitySupplyTypeFId) {
        this.communitySupplyTypeFId = communitySupplyTypeFId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dredge_type.f_name
     *
     * @return the value of t_dredge_type.f_name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dredge_type.f_name
     *
     * @param name the value for t_dredge_type.f_name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dredge_type.f_pic_url
     *
     * @return the value of t_dredge_type.f_pic_url
     *
     * @mbg.generated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dredge_type.f_pic_url
     *
     * @param picUrl the value for t_dredge_type.f_pic_url
     *
     * @mbg.generated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dredge_type.f_desc
     *
     * @return the value of t_dredge_type.f_desc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dredge_type.f_desc
     *
     * @param desc the value for t_dredge_type.f_desc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dredge_type.f_price_desc
     *
     * @return the value of t_dredge_type.f_price_desc
     *
     * @mbg.generated
     */
    public String getPriceDesc() {
        return priceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dredge_type.f_price_desc
     *
     * @param priceDesc the value for t_dredge_type.f_price_desc
     *
     * @mbg.generated
     */
    public void setPriceDesc(String priceDesc) {
        this.priceDesc = priceDesc == null ? null : priceDesc.trim();
    }
}